### ISSUE TITLE
The build process in UI5 Tooling V4 crashes during the `ui5-tooling-less-task` step

### ISSUE THREAD

**Issue by AramSol** [SAP/ui5-tooling#1007]
## Expected Behavior
The ui5 build command should work as it did in UI5 Tooling V3, without any issues during the build process.

## Current Behavior
The build process crashes at the ui5-tooling-less-task step.

## Steps to Reproduce the Issue
- Update your project to use UI5 Tooling V4.
- Ensure that the ui5-tooling-less-task custom task is included in the builder section of your ui5.yaml configuration.
- Run the ui5 build command.
- The build process will crash during the ui5-tooling-less-task step.

## Context
 * UI5 Module Version 4.0.6
 * Node.js Version: 22.2.0
 * npm Version: 10.0.0
 * OS/Platform: windows 11

## Log Output / Stack Trace
![image](https://github.com/user-attachments/assets/4ba71089-f7f9-4327-8603-53109d251b29)

**Comment by d3xter666** [comment]
Dear @AramSol,

Thank you for reaching out. The core issue is that in UI5 Tooling v4 the `DuplexCollection#byGlobSource` has been removed and the packages need to adapt to it: https://sap.github.io/ui5-tooling/v4/updates/migrate-v4/#changes-to-ui5fs

As a workaround, we can suggest that you should downgrade to UI5 Tooling v3 for now.
We'll try to get in touch with the owners of `ui5-tooling-less-task` to fix the issue and make the package compatible with Tooling v4
