### ISSUE TITLE
Unable to load load OData metadata in BTP CF with UI5 CLI v3 and SAPUI5 1.126

### ISSUE THREAD

**Issue by vaibhav0461** [SAP/ui5-tooling#1020]
We have recently switched to UI5 CLI v3 but after this metadata has stopped loading while application load in BTP CF

## Expected Behavior
Metadata is successfully loaded with UI5 CLI v3 and and SAPUI5 1.126 and application screen is loaded

## Current Behavior
404 Not found issue is coming with this..

## Steps to Reproduce the Issue
Application link :- https://edom-consumer-dev.cpp.cfapps.eu10.hana.ondemand.com/612a0c70-cd92-48c0-a0cf-913a4ded1b3a.instanceui-dev.instanceui-0.0.1/index.html
Github Project link:- Branch c4u-discovery-x/tree/master/instanceui in internal Github

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI):  3.11.3
 * Node.js Version: 18.17.1
 * npm Version: 9.6.7
 * Browser *(if relevant)*: Chrome
![Screenshot 2024-09-23 at 4 04 44 PM](https://github.com/user-attachments/assets/659975a7-149b-421a-895a-96b6ac08525c)

**Comment by flovogt** [comment]
Please open an SAP internal development incident. Not here on public github.
