### ISSUE TITLE
Failed to resolve sap.fe.templates.library.js

### ISSUE THREAD

**Issue by komzi111** [SAP/ui5-tooling#1021]
Hi All,

It seems, that last week was published a new version of sap.fe.templates, Since then I have been facing an issue to load this library. I didnt touch the code at all and it stopped working. My manifest JSON file is correct and I included sap.fe.templates in library section. Could you please help how to resolve the issue or what could cause the problem ?

**Comment by RandomByte** [comment]
Kindly fill out our issue template so we can efficiently provide you with support. Especially an error log or similar would be required for us to understand the issue you are facing. Thanks!

**Comment by komzi111** [comment]
An Error from console  is: FUTURE FATAL : Cannot load container container : failed to resolve dependencies sap.fe.templates.library.js.
I am consuming Odata service in my UI5 application and using sap.fe.template library to and deploying to cloud foundry via MTAR. I created this app via Business application studio and everything was created automatically.

**Comment by flovogt** [comment]
@komzi111 sounds like you have a SAP contract, right? Could you please create an SAP support incident on https://support.sap.com/en/index.html. So the SAP experts can have a look at it.

**Comment by komzi111** [comment]
Hello, 
The problem has been resolved, probably by SAP. After 5 days it started to work. Thank you for your comments.
