### ISSUE TITLE
Resolution of framework libraries failed with errors // Failed to resolve library sap.m

### ISSUE THREAD

**Issue by treee111** [SAP/ui5-tooling#1026]
## Expected Behavior
I expect ui5-tooling to build our app with latest UI5 version of 1.108 - 1.108.37

## Current Behavior
The build failes due to not being able to access `@sapui5/distribution-metadata@1.108.37`

## Steps to Reproduce the Issue

1. use latest UI5 version of 1.108 in `ui5.yaml`: 1.108.37
```
framework:
  name: SAPUI5
  version: 1.108.37
```
3. run build using `ui5 build --dest ./dist/resources --clean-dest`, `ui5 build` should also be enough
4. look out for a successful build

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`4.0.9`**
 * Node.js Version: **`v20.14.0`**
 * npm Version: `10.7.0`
 * OS/Platform: `macOS`
 * Browser *(if relevant)*: `unrelevant`
 * Other information regarding your environment *(optional)*: `unrelevant`

## Log Output / Stack Trace

```
<user>@<computer> <directory> % ui5 build
INFO: Using local @ui5/cli installation

info graph:helpers:ui5Framework Using SAPUI5 version: 1.108.37
info ui5Framework:npm:Installer Installing missing package @sapui5/distribution-metadata...

⚠️  Process Failed With Error

Error Message:
Resolution of framework libraries failed with errors:
  1. Failed to resolve library sap.m: Failed to extract package @sapui5/distribution-metadata@1.108.37: No matching version found for @sapui5/distribution-metadata@1.108.37.
  2. Failed to resolve library sap.ui.core: Error already logged
  3. Failed to resolve library sap.ushell: Error already logged
  4. Failed to resolve library sap.collaboration: Error already logged
  5. Failed to resolve library themelib_sap_belize: Error already logged
  6. Failed to resolve library sap.uxap: Error already logged
  7. Failed to resolve library sap.ca.ui: Error already logged


For details, execute the same command again with an additional '--verbose' parameter
```

**Comment by RandomByte** [comment]
There's currently a problem affecting the release of multiple SAPUI5 versions. We are working on resolving this asap.

Affected versions are:

- 1.124.9
- 1.108.37
- 1.96.37

**Comment by RandomByte** [comment]
The issue has been resolved and all missing versions have been published. We apologize for the inconvenience.

**Comment by treee111** [comment]
Thanks! I noticed it today as well
