### ISSUE TITLE
Expected double-quoted property name in JSON at position 21197

### ISSUE THREAD

**Issue by knolljo00** [SAP/ui5-tooling#1029]
Hi colleagues,

I run into following error when running my Azure pipeline:
_Project is using older parentpom version_
I updated the version accordingly but still get the error that a double-quoted property name is expected.

>_- removed SAP internal information (MB) -_

Could you please take a look on that?

Thanks and best regards,
Johannes

**Comment by RandomByte** [comment]
Dear Johannes,

this is the **public** GitHub repository for the [UI5 Tooling project](https://sap.github.io/ui5-tooling/stable/). This project is not associated with the mentioned Azure pipeline. Also, please refrain from posting SAP internal URLs on the public internet.

Best regards,
Merlin
