### ISSUE TITLE
Clarify Release management 

### ISSUE THREAD

**Issue by htammen** [SAP/ui5-tooling#1034]
Currently there is a new release 4.0.12. The only change was an update of ui5/builder dependency from version 4.0.4 to 4.0.5. 
I than had a look at the respective changes of ui5/builder. The git comparision over there said that there are no changes between these releases. 
Why do you release new versions if there are no changes?

**Comment by codeworrior** [comment]
Looking at the [comparison in Github](https://github.com/SAP/ui5-builder/compare/v4.0.4...v4.0.5) shows 16 commits

**Comment by htammen** [comment]
@codeworrior thank you, haven't seen it yesterday night on my smartphone. Sorry for disturbing.

**Comment by codeworrior** [comment]
Never mind ;-)
