### ISSUE TITLE
Exclude folders under webapp from ui5 build process

### ISSUE THREAD

**Issue by rednose84** [SAP/ui5-tooling#124]
## Expected Behavior

With UI5 build I want to exclude folders from build process. 

## Current Behavior

folder structure something like this
├──webapp
 |     ├──controller
 |     ├──view
 |     ├──test
 |     ├──test_screenshots
 |     ├──test_cases

If i run ui5 build all folders which are included in webapp are "uglified" (and something else) and copied to the dist (output) folder. 

It it may be usefull to exclude certain folders from that proccess.

## Affected components *(if known)*
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by immortal-chen** [comment]
is there's any roadmap/plan for this?

**Comment by cschuff** [comment]
I think this is essential since even some standard SAP Web IDE templates contain folders like `localService` within `webapp`.

**Comment by RandomByte** [comment]
If there would be an option to exclude resources, would you expect an excluded resource to be ignored by the UI5 Builder but still to be available in the UI5 Server? Or should it be excluded from both?

**Comment by immortal-chen** [comment]
I'd prefer both.

Since I want to exclude it from the building process, it means I don't want to see it in the generated folder/files. Thus, it will not available in UI5 server too.

**Comment by BenReim** [comment]
I could actually imagine use cases where it would make sense to exclude folders from the build process, yet still have them available through the ui5-server. 

For instance, think of test-resources which a developer would want to leverage during development time, yet might not want them to be included in a build result.

**Comment by RandomByte** [comment]
So two configuration options it is 😄

One general exclude and one builder specific. 

Thank you for your feedback.

**Comment by RandomByte** [comment]
The builder specific exclude has been implemented with https://github.com/SAP/ui5-builder/pull/254 and related PRs.

Documentation is [still pending](https://github.com/SAP/ui5-project/pull/180) but **the feature can already be tested with UI5 CLI v1.5.0** as described here:
https://github.com/SAP/ui5-project/pull/180/files?short_path=7b182d5#diff-7b182d5ba2fea830f66aca8de9366067

Feedback is highly appreciated!

@rednose84 I think this resolves your issue, hence I'll close it.

For the general exclude option that I proposed during the discussion I have created a new issue #155. Please leave feedback there it you want to see that implemented as well!

**Comment by RandomByte** [comment]
Now [documented in master](https://github.com/SAP/ui5-project/blob/master/docs/Configuration.md#structure) 🎉
