### ISSUE TITLE
Allow SAPUI5 libraries to be consumed as npm packages

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-tooling#130]
## Expected Behavior
SAPUI5 libraries are provided as npm packages and can therefore be used along side the `ui5-tooling`

## Current Behavior
Currently, if an app depends on SAPUI5 libraries, it cannot leverage the ui5 tooling as SAPUI5 libraries cannot be referenced as dependencies.

**Comment by codeworrior** [comment]
Do I get it correctly: you mean SAPUI5 libs in contrast to OpenUI5 libs?

**Comment by BenReim** [comment]
I mean SAPUI5 libraries should be available as npm packages in the same way that openui5 libraries are already published as npm packages.  

Currently, apps that makes use of SAPUI5 libraries can't migrate to the `ui5-tooling` as those libraries can not be consumed by npm.

**Comment by RandomByte** [comment]
Hey @BenReim, this is something we are working on right now (and already did for the last couple of months). We also involved the OpenUI5 community in some decisions via Slack. Note that the SAPUI5 libraries will most probably be released exclusively to the npm.sap.com registry.

The whole thing is apparently not as simple as for OpenUI5. I think you can expect something in Q3 by the latest.

I'll close this incident as the topic is not directly related to the UI5 Tooling. Feel free to reach out to us in the OpenUI5 Slack if you have further questions.

**Comment by RandomByte** [comment]
As there is currently no better place on GitHub to track this issue (unavailability of SAPUI5 libraries as npm packages), we'll reopen this issue and update it once relevant progress has been made.

**Comment by js1972** [comment]
Any updates on this? Is there an alternative to get the UI5 tooling to work with the sapui5 sdk download from tools.hana.ondemand.com maybe?

**Comment by stesap** [comment]
I like to ask as well 😄 Any updates?
We relay on SAPUI5 resources, because of VizFrame (sap.viz.ui5 namespace). This is not in OpenUI5, yet.

**Comment by RandomByte** [comment]
We are actively working on providing SAPUI5 libraries as official npm packages. Current ETA is Q1 2020.

In the meantime you might want to try some of the workarounds the community came up with. I think the latest one is https://blogs.sap.com/2019/11/05/end-to-end-setup-of-local-development-environment-with-ui5-tooling/
Also feel free to ask around in the OpenUI5 Slack Channel!

**Comment by superwangnan** [comment]
Hi team,
it's end of Q1, any update for that? That's important for us  :). Thanks so much in advanced.

**Comment by RandomByte** [comment]
Hey, the current ETA is end of this month. We are working hard on making that happen 👍 

We try to document our progress publicly in https://github.com/SAP/ui5-tooling/issues/204

**Comment by RandomByte** [comment]
Thank you all for bearing with us.

**SAPUI5 libraries can now be consumed using the UI5 Tooling 2.0** 🎉 

- [Announcement Blog Post](https://blogs.sap.com/2020/04/01/introducing-ui5-tooling-for-sapui5-projects/)
- [Technical Blog Post](https://blogs.sap.com/2020/04/01/ui5ers-buzz-49-the-ui5-tooling-and-sapui5-the-next-step/)
- [Documentation](https://sap.github.io/ui5-tooling/pages/SAPUI5/)
