### ISSUE TITLE
Cannot dockerize [sample] app

### ISSUE THREAD

**Issue by IObert** [SAP/ui5-tooling#132]
## Expected Behavior
I would like to dockerize the running app. I took the sample app and added the following `Dockerfile` to the project root:
```
FROM node:9-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
COPY package*.json ./

RUN npm install
# If you are building your code for production
# RUN npm install --only=production

# Bundle app source
COPY . .


EXPOSE 8080
CMD [ "npm", "start" ]
```

Then I call these commands to build and start the image:
```
docker build --tag simple1 .
docker run -p 8080:8080 simple1
```
## Current Behavior
I see that the web server supposedly started, but I cannot access the demo app.

<img width="535" alt="screen shot 2019-02-11 at 16 17 11" src="https://user-images.githubusercontent.com/1873245/52572624-82333e80-2e18-11e9-9c27-6930e7853c10.png">

![screen shot 2019-02-11 at 16 24 00](https://user-images.githubusercontent.com/1873245/52573028-75fbb100-2e19-11e9-8bb7-8df7733e0da5.png)

I would like to dockerize this to test if the app can be built successfully.

## Steps to reproduce the issue
1. Clone https://github.com/SAP/openui5-sample-app
2. Add Dockerfile
3. Create docker image
```
docker build --tag simple1 .
docker run -p 8080:8080 simple1
```
4. Access localhost:8080

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: most recent
- Node.js Version: node:9-alpine
- npm Version: node:9-alpine
- OS/Platform: OSX
- Browser *(if relevant)*: {...}
- Other information: {...}

## Affected components *(if known)*
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace

**Comment by RandomByte** [comment]
You'll need to modify the start script by appending the `--accept-remote-connections` flag.

By default the UI5 Server only accepts connections from localhost. Your connection from your host to the Docker container is routed via the docker internal network stack, making the connection appear as an external one to the container.
