### ISSUE TITLE
Programmatically use ui5-builder

### ISSUE THREAD

**Issue by cschuff** [SAP/ui5-tooling#138]
Is there a way to have `ui5Builder.build()` just do the same thing as calling `ui5 build` from the command line? 

As far as I understood from your tests that should be possible but needs the 'application tree' as js object:
```js
builder.build({
  tree: applicationTree,
  destPath
}).then(...)
```

How can I create that tree from ui5.yaml?

Thanks for help!

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by vobu** [comment]
me thinks
```
require('@ui5/project').normalizer.generateProjectTree({
    cwd: process.cwd()
})
```
might be what your looking for

**Comment by cschuff** [comment]
That is exactly what I was looking for :) Will try!

**Comment by RandomByte** [comment]
@vobu correct!

@cschuff you can also have a look into the CLI implementation: https://github.com/SAP/ui5-cli/blob/master/lib/cli/commands/build.js#L71

The CLI implementation has a low footprint on intention. We explicitly support use cases where modules are being used independently from the CLI 👍 

I'll close this but let us know if any problems come up!
