### ISSUE TITLE
Tooling builds library to resources subfolder, while app doesn't.

### ISSUE THREAD

**Issue by kovboyjder** [SAP/ui5-tooling#156]
We recently moved to the new tooling for our apps and libraries in our CI. With the libraries it did break some stuff as they are added to dist/resources folder. This means that when we run our deploy task it deploys straight from the dist/ and the path then becomes obscured and the Gateway server can't figure it out. Is that a bug in the tooling or should we make our CI behave?

## Expected Behavior
UI5 build would add library straight to the dist folder 

## Current Behavior
ui5 build adds library to /dist/resources

## Steps to reproduce the issue
1. Create a library
2. Run UI5 Build
3. See dist folder

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.2.1`
- Node.js Version: `11`
- npm Version: `6.4.1`
- OS/Platform: `Windows 10/Docker image based on node:latest`
- Browser *(if relevant)*: `{...}`
- Other information: `{...}`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
{...}
```

**Comment by RandomByte** [comment]
The content of the `dist` directory is supposed to reflect the directory structure as expected at UI5 runtime. By default, libraries are loaded from `/resources/<library namespace>`.

This is also documented here: https://github.com/SAP/ui5-builder#library ("virtual directories" become physical directories in `dist`)

This allows to build an app with all its dependencies and then just start any http server on the dist directory.

Can you possibly adapt your deploy script to transform the structure to what is expected on your server platform?

**Comment by kovboyjder** [comment]
All good. We have done that already. Just wanted to highlight it
