### ISSUE TITLE
ui5 tree / serve command does not give output

### ISSUE THREAD

**Issue by NoelHendrikx** [SAP/ui5-tooling#16]
## Expected Behavior
After ui5 init I expected to have results when launching ui5 tree. Also when launching ui5 serve I expect to have a webserver (localhost)

## Current Behavior
Both ui5 tree and serve give no output and it looks like the command line is expecting something more. I have to abort the command line to return to the terminal.

## Steps to reproduce the issue
1. install node 10.4.1.
2. npm install --global @ui5/cli
3. ui5 --version -> 0.0.2
4. ui5 init
5. ui5 serve or ui5 tree

After adding --verbose I see a lot of dependencies being checked and finally the cli looks like to be stopped.

`verb normalizer:translators:npm   dependencies:
verb normalizer:translators:npm    [ { id: 'gulp-css-condense',
verb normalizer:translators:npm        version: '1.1.2',
verb normalizer:translators:npm        path:
verb normalizer:translators:npm         '/Users/Noel/XXXX/myapp/node_modules/gulp-css-condense',
verb normalizer:translators:npm        dependencies: [Array] },
verb normalizer:translators:npm      { id: 'gulp-ruby-sass',
verb normalizer:translators:npm        version: '3.0.0',
verb normalizer:translators:npm        path:
verb normalizer:translators:npm         '/Users/Noel/myapp/node_modules/gulp-ruby-sass',
verb normalizer:translators:npm        dependencies: [Array] },
verb normalizer:translators:npm      { id: 'ui5-schemas',
verb normalizer:translators:npm        version: '0.3.1',
verb normalizer:translators:npm        path:
verb normalizer:translators:npm         '/Users/Noel/myapp/node_modules/ui5-schemas',
verb normalizer:translators:npm        dependencies: [Array] } ] }
`
This is an existing ui5 project with gulp files setup already.

## Context
- OS/Platform: Mac 
- Node.js Version: 10.4.1
- npm Version: 6.1.0
- Browser *(if relevant)*: {...}
- Other information: {...}

## Affected components
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [X] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)

## Stack trace/log output
```
{logs}
```

**Comment by NoelHendrikx** [comment]
Removed dependencies to gulp-css-condense and others in manifest.json, and the ui5 tree command works.

**Comment by janmattfeld** [comment]
@RandomByte istalled `@ui5/cli` version is and was `0.2.1`. The `package.json` states `^0.2.1`.

**Comment by RandomByte** [comment]
@janmattfeld that's odd. We expected this to be fixed with https://github.com/SAP/ui5-project/pull/15 . This might a different bug.

It would be great if you could [create a new issue](https://github.com/SAP/ui5-project/issues/new) and provide the project setup this can be reproduced with. Maybe an empty project with a specific set of npm dependencies is already sufficient.
