### ISSUE TITLE
Request: Deploy to ABAP / SCP 

### ISSUE THREAD

**Issue by NoelHendrikx** [SAP/ui5-tooling#17]
Are there any intentions to implement also a deployment option to ABAP or SCP platform? Or do I need grunt / gulp (gulp-nwabap-ui5uploader) to do so?

## Affected components
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)

**Comment by RandomByte** [comment]
Thanks for the report! Like we said at UI5con: Not planned as of today.

Right now the plan is to rather provide a plugin mechanism to allow for third-parties to develop such a tool and for any developer to use it through the UI5 CLI is wished.

I'll leave this issue open to have this topic visible and to track any progress (in whichever direction).

**Comment by nlsltz** [comment]
@RandomByte @matz3 are there any docs out there to get started with plugin development at the moment?

**Comment by RandomByte** [comment]
No, we don't even have a concept (yet implementation) for that yet. Also see https://github.com/SAP/ui5-tooling/pull/4

**Comment by mauriciolauffer** [comment]
I've started working on something for it, feel free to contribute:

https://github.com/mauriciolauffer/ui5-deployer

**Comment by flovogt** [comment]
@mauriciolauffer Thanks a lot for mentioning your project here.
Currently, it's not planned to introduce a deployment functionality into the UI5 Tooling. In future there might be a hook (see https://github.com/SAP/ui5-tooling/issues/490) where a project like the [ui5-deployer](https://github.com/mauriciolauffer/ui5-deployer) can be attached to.

**Comment by mauriciolauffer** [comment]
@flovogt please, don't create any deployment feature inside ui5-builder! See my [comment](https://github.com/SAP/ui5-tooling/issues/490#issuecomment-1515640145)
