### ISSUE TITLE
Slack Invite not working

### ISSUE THREAD

**Issue by schealex** [SAP/ui5-tooling#188]
## Expected Behavior
https://slackui5invite.herokuapp.com/
should take you to a page where you can enter email address so you can receive an invite

## Current Behavior
showing a heroku error page

## Steps to reproduce the issue
visit https://slackui5invite.herokuapp.com/

**Comment by RandomByte** [comment]
Hey @schealex, these services are hosted by members of our community.

I can confirm that https://slackui5invite.herokuapp.com/ doesn't seem to work.

However, the one we link in the readme is https://join-ui5-slack.herokuapp.com/ and that one seems to work fine. Can you confirm that?

**Comment by schealex** [comment]
@RandomByte the link you provided is working fine but i am not able to find that one in the readme.
the current readme is showing the link i mentioned which does not work, maybe this needs to be updated? https://github.com/SAP/ui5-tooling/blame/master/README.md#L33

**Comment by RandomByte** [comment]
I see. I was referring to the badge at the top of the readme: https://github.com/SAP/ui5-tooling/blame/master/README.md#L6

We updated that link to the new app but seem to have forgotten about the other link. Thanks! We'll fix that.

**Comment by akudev** [comment]
The actual, official link is https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com

**Comment by flovogt** [comment]
@akudev we had in the past issues with the CF link. Therefore we switched to an official slack link. https://github.com/SAP/ui5-tooling/pull/810
