### ISSUE TITLE
.properties Files in UTF8 not correkt encoded

### ISSUE THREAD

**Issue by hauntedhill** [SAP/ui5-tooling#190]
## Expected Behavior
My propertie files have the encoding UTF-8. So i try the following setting in the ui5.yaml:

builder:

  customTasks:
    ...
  resources:
    configuration:
        propertiesFileSourceEncoding: "UTF-8"
    excludes:
        ...

Now i would like to see that my characters like äöü encodet in for example "\u00e4" or "\u00fc".

## Current Behavior
In the i18n files i see "\u00c3\u00a4" for an "ä". It is the same in the component-preload.js for the manifest.json and the corresponding i18n file.

## Steps to reproduce the issue
1. Save a i18n file in UTF8 and save a character like "ä"
2. execute ui5 build
3. look at the i18n file in the dist folder and the component-prelod.js (manifest.json and i18n file)

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.11.0`
- Node.js Version: `10.16.3`
- OS/Platform: `WIN/LINUX`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

```

**Comment by RandomByte** [comment]
Hey @hauntedhill, I tried to reproduce this with the [openui5-sample-app](https://github.com/SAP/openui5-sample-app), which contains umlauts in the german i18n file. Apparently I'm getting different results than you. `ä` for instance is correctly escaped as `\u00e4`.

Could you please test this in the sample app as well?

1. `git clone git@github.com:SAP/openui5-sample-app.git`
2. `cd openui5-sample-app && npm install`
3. `ui5 build`

`dist/i18n/i18n_de.properties` should now contain:

```properties
TITLE=Todos
INPUT_PLACEHOLDER=Was muss getan werden?
ITEM_LEFT=Eintrag \u00fcbrig
ITEMS_LEFT=Eintr\u00e4ge \u00fcbrig
CLEAR_COMPLETED=Erledigte Eintr\u00e4ge entfernen
```

**Comment by hauntedhill** [comment]
I am sorry i have set the configuration at the wrong position in the config

**Comment by RandomByte** [comment]
Glad to hear that. We should really add some validation for the `ui5.yaml` 😓 (CC: @matz3)
