### ISSUE TITLE
Links broken in documentation

### ISSUE THREAD

**Issue by ckoutsiaris** [SAP/ui5-tooling#194]
In documentations in section Modules/Builder in Tasks and Processors, the links are broken
https://sap.github.io/ui5-tooling/pages/Builder/#tasks

Where should they point?

## Expected Behavior
Links to documentation

## Current Behavior
404

## Steps to reproduce the issue
Visit https://sap.github.io/ui5-tooling/pages/Builder/#tasks and click the links

**Comment by RandomByte** [comment]
Hey, thanks for reporting! I think this is a duplicate of https://github.com/SAP/ui5-builder/issues/374. We are already working on fixing the links.

**Comment by ckoutsiaris** [comment]
Cool thanks!
