### ISSUE TITLE
Failed to run ui5 build self-contained with SAPUI5 libs

### ISSUE THREAD

**Issue by diegodossantos95** [SAP/ui5-tooling#208]
Hi all,
Could you confirm if the self-contained build is compatible with SAPUI5 libs from a repository other than npm?
I am asking that because my project is using the SAPUI5 libs from CDN and when I run the build self-contained I see a series of errors like:
`missing module sap/m/MessageBox.js, required by com/sap/my/module/myfile.js`
I don't know if I am missing a configuration, but the documentation doesn't request any config other than ui5.yaml.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.13.1`
- Node.js Version: `11.4.0`
- npm Version: `6.13.6`
- OS/Platform: `MacOS Catalina 10.15.3`

## Affected components *(if known)*
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by vobu** [comment]
Hi,
CDN and build-tooling don't go together - you need the UI5 libs installed for `ui5 build` to work.
Additionally, `ui5 build` is (currently) limited to OpenUI5 and not SAPUI5.
hth, v.

**Comment by RandomByte** [comment]
The UI5 Tooling is only capable of bundling resources coming from the [internal translators](https://sap.github.io/ui5-tooling/pages/Project/#translators), typically the npm translator.

You should wait for the SAPUI5 libraries to be available as npm packages: https://github.com/SAP/ui5-tooling/issues/130
