### ISSUE TITLE
Missing core module for self contained buildui5 

### ISSUE THREAD

**Issue by vickyokrm** [SAP/ui5-tooling#209]
## Current Behavior
Self contained builder returns missing core module error. Nevertheless the build process was successful.

## Steps to reproduce the issue
1. Open an UI5 project  uses UI5 tooling
2. Build using UI5 build self-contained
3. Watch the logs to find this error.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.13.0`
- Node.js Version: `11.7.0`
- npm Version: `6.5.0`

## Affected components *(if known)*

- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
WARN lbt:analyzer:JSModuleAnalyzer Cannot evaluate registerPreloadedModules: 'Identifier'
ERR! lbt:bundle:Resolver **** error: missing module sap/ui/support/Bootstrap.js, required by sap/ui/core/Core.js
WARN lbt:analyzer:JSModuleAnalyzer Cannot evaluate registerPreloadedModules: 'Identifier'

```

**Comment by matz3** [comment]
The reason for this error is that the sap.ui.core library has an optional dependency to the sap.ui.support library. In case you do not have a dependency on the sap.ui.support library, this error is shown but it can be safely ignored.

We need to find a better way to differentiate between such optional dependencies and actual missing dependencies.
