### ISSUE TITLE
"API Reference" link in readme leads to 404

### ISSUE THREAD

**Issue by akudev** [SAP/ui5-tooling#21]
## Current Behavior
The "API Reference" link in the "Documents" section of the readme file (not far from the top) leads to https://github.com/pages/SAP/ui5-tooling, which is a 404. Not sure where it was supposed to lead... 

See https://github.com/SAP/ui5-tooling/blob/master/README.md

**Comment by RandomByte** [comment]
Will be fixed once #18 is resolved.

**Comment by RandomByte** [comment]
Should be fixed now! 👍
