### ISSUE TITLE
Provide UI5 Best Practices linter support

### ISSUE THREAD

**Issue by HoffmannThomas** [SAP/ui5-tooling#212]
## Expected Behavior
Proper UI5 linting

## Current Behavior
No linting

## Steps to reproduce the issue
1. Use SDK pipeline and configure ES6+ support (https://github.com/SAP/cloud-s4-sdk-pipeline-lib/blob/master/vars/checkUi5BestPractices.groovy#L55-L64 + https://github.com/SAP/cloud-s4-sdk-pipeline/blob/master/configuration.md#lint)
2. Review lint result
3. Attempt to get the same result locally

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by nils-kasseckert** [comment]
To execute the UI5 linting from the cloud SDK locally you can use the [UI5 Lint Script](https://github.com/SAP/cloud-s4-sdk-pipeline-lib/tree/master/resources/check-ui5-best-practices).

**Comment by RandomByte** [comment]
As stated [here](https://github.com/SAP/openui5/issues/2482#issuecomment-597883520) and also discussed via mail, the `@sap/di.code-validation.js` module will not be open sourced in the foreseeable future. Therefore I don't see how a good integration into the UI5 Tooling could be achieved.

Regarding linting in general, I would expect there to be an open source ESLint plugin, offering UI5 specific rules. This could then be used directly with ESLint and independently of the UI5 Tooling. I currently don't see a reason for implementing code linting capabilities into the UI5 Tooling.

Therefore closing this issue in favor of https://github.com/SAP/openui5/issues/2482
