### ISSUE TITLE
How to build the "most optimized" package by ui5 command

### ISSUE THREAD

**Issue by superwangnan** [SAP/ui5-tooling#224]
Hi team,
We can build the distribution package by ui5 build command. How can we build the "most optimized" package?
As I known, we can use:
"ui5 build --all" and "ui5 build self-contained --all", according to my test, the self-contained package will be smaller than the first one. But both of them contain the .dbg file.
My questions:
1. what's the difference between different build pattern? do we have detail document for that?
2. If we want to get the 'most optimized' package, any other operation we can do on the built package? Maybe, for example, remove the .dbg file manually or others.

Thanks.

**Comment by RandomByte** [comment]
Hey, the -dbg files are still included in case you want to debug the running application (e.g. using the `?sap-ui-debug=true` URL parameter).

However, you can skip the creation of these files by excluding the corresponding task: `ui5 build self-contained --all --exclude-task=createDebugFiles`.

We should definitely add documentation on this topic, and will do as part of this issue: https://github.com/SAP/ui5-builder/issues/113

Therefore closing this. Thanks for reporting! Feel free to get back to us if you have further questions.

**Comment by BenjyTec** [comment]
As a hint to anyone still looking for it, in CLI V3 the `createDebugFiles` has been replaced by
`--exclude-task=minify`. This will create a build without the dbg and map files.
