### ISSUE TITLE
Same JavaScript source text formatting rules across IDEs

### ISSUE THREAD

**Issue by born2dev** [SAP/ui5-tooling#232]
Dear UI5-Team,
suppose several developers working on the same UI5 project, and each of them uses a different IDE: Eclipse, IntelliJ, WebIDE, VSCode, etc..
Is there a way to get to the same JavaScript source text formatting rules?

**Comment by vobu** [comment]
one word: prettier
https://prettier.io/

**Comment by htammen** [comment]
And https://editorconfig.org/

**Comment by matz3** [comment]
Thanks @vobu and @htammen for your comments.
I guess that question is rather unrelated to this project, but we're mainly using EditorConfig.
