### ISSUE TITLE
ux-specification and ux-ui5-tooling dependencies problem

### ISSUE THREAD

**Issue by kepair** [SAP/ui5-tooling#241]
## Expected Behavior
When using the app generator to create a List report (I tried v2 and v4), the tool generates the files and install the required dependencies.

## Current Behavior
When using the app generator to create a List report (I tried v2 and v4), the tool generates the files but can't install two SAP dependencies:

```json
"@sap-ux/ui5-tooling": "^0.0.85",
"@sap-ux/specification": "1.76.8"
```

```
Copying template...
Installing dependencies...
npm.cmd ci: npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sap-ux/specification/-/specification-1.76.8.tgz

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@sap-ux/ui5-tooling/-/ui5-tooling-0.0.85.tgz
npm ERR! 404
npm ERR! 404  '@sap-ux/ui5-tooling@0.0.85' is not in the npm registry.
```

## Steps to reproduce the issue
1. Use the app generator
2. Choose List Report v2 or v4 and fill the details
3. Click generate

## Workaround
The correct dependencies are:

```
"@sap/ux-ui5-tooling": "^1.0.6",
"@sap/ux-specification": "^1.76.8"
```

## Context
- UI5 Module Version : `2.0.3`
- Node.js Version: `12.16.1`
- npm Version: `6.13.4`
- OS/Platform: `Windows 10`
- IDE: `vscode`

Is this a typing error or is there something I'm not understanding?

Kind regards,
Pedro

**Comment by RandomByte** [comment]
> Use the app generator

Which app generator are you referring to? This seems to be an issue with that generator and not with the UI5 Tooling.

Please also note that `@sap/ux-ui5-tooling` is not part of this project, it internally makes use of the `@ui5/cli` (which *is* part of this project).

**Comment by kepair** [comment]
Hi,

I'm using the SAP Fiori - Application Generator. Is that something part of the tooling?

Kind regards,
Pedro

**Comment by RandomByte** [comment]
Apparently, the SAP Fiori - Application Generator is not part of the UI5 Tooling project. It is rather part of the SAP Fiori tools project, which is not open source as of today.

Kindly check the comments on this related blog post as it seems that similar issues have already been mentioned there: https://blogs.sap.com/2020/06/22/sap-fiori-tools-is-generally-available.-increase-the-efficiency-of-developing-sap-fiori-elements-apps/

You can also ask questions on the extension page: https://marketplace.visualstudio.com/items?itemName=SAPSE.sap-ux-fiori-tools-extension-pack&ssr=false#qna

And on the SAP Community Website: https://community.sap.com/

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project.

**Comment by kepair** [comment]
Update:

The problem with the dependencies got solved after reinstalling the tool set. It was probably a problem in my environment.

Kr,
Pedro
