### ISSUE TITLE
Verification failed while extracting @sap/di.code-validation.xml@1.1.20

### ISSUE THREAD

**Issue by Madhusudhan7** [SAP/ui5-tooling#255]
## Expected Behavior
Successful build of project.

## Current Behavior
Unsuccessful build of project due to  Verification failed while extracting @sap/di.code-validation.xml@1.1.20

## Steps to reproduce the issue
1. Create new Fiori List Report Elements Project
2. Build
3. Error

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.71.11`
- Node.js Version: `webIDE`
- npm Version: `webIDE`
- OS/Platform: `webIDE`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
1:07:26 PM (DIBuild) npm ERR! code EINTEGRITYnpm ERR! Verification failed while extracting @sap/di.code-validation.xml@1.1.20:npm ERR! Verification failed while extracting @sap/di.code-validation.xml@1.1.20:npm ERR! sha512-Ws6b+8WRi336aOq7XMwZM7CJPYyzesQnEvejGz6z3z466un1UPUfLdAy6k/YDwwpMGw2PCauckm1LtwgyXD9Lg== integrity checksum failed when using sha512: wanted sha512-Ws6b+8WRi336aOq7XMwZM7CJPYyzesQnEvejGz6z3z466un1UPUfLdAy6k/YDwwpMGw2PCauckm1LtwgyXD9Lg== but got sha512-YhiKPaDb0hTRPVkSoMeV1nb+45QpsWiZ3aIKOI7y0ROglndFD2kodw1K69UwMFgl5Bw3YFR831afqr4vi3Atkw==. (5150651 bytes)
```

**Comment by matz3** [comment]
This might be due to the switch from npm.sap.com to the official npm registry. Usually deleting the `package-lock.json` and re-trying an `npm install` should solve it.

Note that this issue is not related to the UI5 Tooling modules (@ui5/*). Next time, please use the corresponding support channels to get help.
