### ISSUE TITLE
Application folder structure to get UI5 Tooling working

### ISSUE THREAD

**Issue by born2dev** [SAP/ui5-tooling#257]
Dear UI5-Team,
The folder structure of my application is as follows (hosted by Tomcat in production):

src/main/webapp:

- index.html, excerpt:
  data-sap-ui-resourceroots='{"my.ns" : "./"}'
  new ComponentContainer({ name : "my.ns.component0",

- ui5.yaml, excerpt:
  resources:
  configuration:
    paths:
      webapp: src/main/webapp/

src/main/webapp/component0 (namespace: my.ns.component0):

 - Component.js
 - manifest.json, excerpt:
   "dependencies": 
      {"components": {
	    "my.ns.component1": {
 - ...

src/main/webapp/component1 (namespace: my.ns.component1):

 - Component.js
 - manifest.json
 - ...

So component0 is the main component which uses other components, component1 among others.

Is there any chance to get such a folder structure working with UI5 Tooling?

"Ui5 serve" leads to 
"Failed to read manifest.json for project name: ENOENT: no such file or directory, open '.../src/main/webapp/manifest.json'"

Pointing paths->webapp (ui5.yaml) to src/main/webapp/component0 starts the server, however component1 is not found then.

**Comment by RandomByte** [comment]
Hey, a project of type `application` may only contain a single component. Currently, multiple components need to split into multiple projects with one being of type `application` and the others of type `library`. Here you can find an example of such a project: https://github.com/flovogt/ui5con20-ui5-routing

Please also see our documentation here: https://sap.github.io/ui5-tooling/pages/Builder/#application
