### ISSUE TITLE
Allow external datasource connection

### ISSUE THREAD

**Issue by DenisTis** [SAP/ui5-tooling#266]
Dear all, 

thank you for the great work. This is a really nice repo. However, currently it only can be used for simple train cases.
Sometimes application requires backend data and  if I provide correct datasource and datasource model in the manifest file, I get CORS issue.

Could there be some proxy being added to enable serving of external datasource?

**Comment by matz3** [comment]
There are several custom taks and middleware available here: https://petermuessig.github.io/ui5-ecosystem-showcase/
For your use-case the `ui5-middleware-simpleproxy` can be used to establish a backend connection via a proxy.
