### ISSUE TITLE
--include-task=generateLibraryPreload didn't work

### ISSUE THREAD

**Issue by Victor716** [SAP/ui5-tooling#268]
Hi 

I want to include the task --include-task=generateLibraryPreload

`ui5 build preload --config=ui5.yaml --clean-dest --dest dist --include-task=generateLibraryPreload generateLibraryManifest`

but the log didn't show anything about the tasks included

builder:builder Building project little.demo not including dependencies...
info builder:builder �  (1/1) Building project little.demo
info builder:builder application little.demo � (1/8) Running task escapeNonAsciiCharacters...
info builder:builder application little.demo � (2/8) Running task replaceCopyright...
info builder:builder application little.demo � (3/8) Running task replaceVersion...
info builder:builder application little.demo � (4/8) Running task generateFlexChangesBundle...
info builder:builder application little.demo � (5/8) Running task generateComponentPreload...
info builder:builder application little.demo � (6/8) Running task createDebugFiles...
info builder:builder application little.demo � (7/8) Running task uglify...
info builder:builder application little.demo � (8/8) Running task generateVersionInfo...
info builder:builder Build succeeded in 588 ms

By the way, do u know any references about ui5 build standard tasks? I tried very hard but only find the docs. There's no concrete tutorials but simply some implicit codes. I'm so confused when using ui5 tooling. 

Can u help me?

Victor

**Comment by RandomByte** [comment]
Is your project of type `library`? There is no library-preload generation for `application` projects.

Yes, it's currently not easy to get a comprehensive list of the tasks available. We want to rework some of that in the future. Until then I think @matz3 started improving the documentation a bit? Apparently, I can't remember the details there.

**Comment by Victor716** [comment]
Hi RandomByte,
Glad to hear from you. Yes, I'm having an application instead of library. I tried to 
`npm i sap.ui.m` and the task ran. But this task didn't meet my expectation. I thought it would bundle all the controls that used in one module. Like, if sap.m.Text is used in the project, it would be bundled instead of using the whole sap.m module where it resides.

Victor

**Comment by RandomByte** [comment]
> I thought it would bundle all the controls that used in one module. 

I think what you are looking for might be the self-contained build. You can find a demo setup for that here: https://github.com/SAP/openui5-sample-app#building

**Comment by matz3** [comment]
@RandomByte here's my current state of documenting the tasks: https://github.com/SAP/ui5-tooling/pull/270
