### ISSUE TITLE
project-shims : npm package build issue

### ISSUE THREAD

**Issue by nbmedikonda** [SAP/ui5-tooling#276]
## Current Behavior
Configured  the xlsx dependency as a UI5 project using a "Project Shim.
https://www.npmjs.com/package/xlsx

it copied all the resources to the path mentioned in yaml as expected.But the extra name is  added to the each file and folder.
 
example : the folder name is dist but the generated folder name is xlsxdist
Result after build - 
![image](https://user-images.githubusercontent.com/43180934/99625232-6ac5b400-29f5-11eb-93d1-951a7386af93.png)

 

**package.json**

  "ui5": {
    "dependencies": [
      "xlsx",
      "@okta/okta-signin-widget"
    ]
  }

**ui5.yaml**

---
specVersion: "2.2"
kind: extension
type: project-shim
metadata:
  name: ahm.thirdparty
shims:
  configurations:
     xlsx:
       specVersion: "2.2"
       type: module
       metadata:
         name: xlsx
       resources:
         configuration:
           paths:
             /resources/thirdparty/xlsx: ''

## Affected components *(if known)*

- [ x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
In your configuration, could you please make the following change to add a trailing slash:

```diff
- /resources/thirdparty/xlsx: ''
+ /resources/thirdparty/xlsx/: ''
```

Also refer to the example at: https://sap.github.io/ui5-tooling/pages/extensibility/ProjectShims/#example-a

Please let us know whether this resolves the issue.

**Comment by nbmedikonda** [comment]
@RandomByte - its Resolved after adding trailing slash
