### ISSUE TITLE
cli 1.7.0 with utf-8 is not work for launchpad shell header

### ISSUE THREAD

**Issue by SupayaT** [SAP/ui5-tooling#287]
## Expected Behavior
Can display the correct UTF-8 text on launchpad shell header.

## Current Behavior
I use the last published version of cli  (1.7.0 version) to build ui5 application and deploy to the system with web-ide. Then, The launchpad shell header display with ������ So, I see the component-preload file on the i18n_th text is encoded to ascii. Let me know how could I do for this case or maybe add any code in ui5.yaml file?

## Steps to reproduce the issue
1. Create new simple ui5 application and use i18n model for application title from i18n
2. Create i18n_th and use some Thai text for the application title
3. On file ui5.yaml,  add the following code after line of metadata-name
_resources:
    configuration:
        propertiesFileSourceEncoding: "UTF-8"_
4. Build the application and deploy to system.

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.68.1`
- Node.js Version: `{...}`
- npm Version: `{...}`
- OS/Platform: `{...}`
- Browser *(if relevant)*: `Chrome`
- Other information: `{...}`

## Affected components *(if known)*

- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
{...}
```

**Comment by ekansh005** [comment]
Hi @RandomByte,

I am having exact same issue with Finnish characters. I checked the mentioned SAP note but it can't be installed as SAP system is on SAP_UI 754 SP 08. I checked the correction and the code is already present in the mentioned ABAP class.
The `i18n_fi` file contains APP_TITLE as `Toimittajan Hintatyökalu` which is converted to `Toimittajan Hintaty\u00f6kalu` in the dist folder and is deployed the same way.
When I access the app from FLP on ABAP stack, the title doesn't reflect the unicode character at all i.e. `ö` is missing in the title. On inspecting the DOM, it has empty space in place of `ö` character.
![image](https://user-images.githubusercontent.com/439184/166677448-bb850dd4-f691-4fad-86bf-0187b4dfd3cd.png)
![image](https://user-images.githubusercontent.com/439184/166677225-73a89f03-1bc2-4bac-b57f-2dbb03105643.png)

SAP_UI	754	0008	SAPK-75408INSAPUI

![image](https://user-images.githubusercontent.com/439184/166677712-ecff321e-f9be-44ce-971c-70d511faa8e5.png)
![image](https://user-images.githubusercontent.com/439184/166677801-cdf7ae42-f35d-4d03-8ffd-e0f073fb669e.png)

Please help.

BR, Ekansh

**Comment by ekansh005** [comment]
Hi @RandomByte, 

Thanks for your reply. We were in a hurry, so I excluded the task `escapeNonAsciiCharacters` for now and deployed that version. However, I noticed a few things after doing all this:
- we had recently upgraded our stack to 754 and the app wasn't changed in a while
- as the note suggested, we still need to redeploy our app so that texts can be updated. Since the app was old, we hadn't redeployed it to test if it worked with Unicode characters.

I will test this soon with another app and let you know here. Hopefully it works fine.

**Comment by ekansh005** [comment]
Hi @RandomByte,

Okay so I tested this with another application of mine which was not yet deployed again since the upgrade of SAP_UI 754 component. I just deployed the app again and the title was displaying the Finnish characters properly.

Thanks for your support.
