### ISSUE TITLE
Build from webapp to webapp: html files are empty

### ISSUE THREAD

**Issue by GuillaumedesPommareSAP** [SAP/ui5-tooling#303]
Hello,

Please confirm if it is a bug, a feature request, or a wrong use of ui5-cli and underlying modules.

## Context
We already defined a UI5 build pipeline which generates from Typescript source code a UI5 ready to serve code. This pipeline includes babel and some transformers, use a a source our `src` and `test` directories, and outputs into the standard webapp folder.

We use then ui5 dist so that these generated resources get reworked (uglyfication, copyright, ...)
Because our next build steps (packaging) are handled by maven we expect to have the final folder be `webapp` , so we do not use the default `dist` output folder but we add `--dest ./webapp` to the command line.

## Expected Behavior
In `webapp`, we get all resources reworked by required tasks and processors.

## Current Behavior
In `webapp`, some resources are not properly reworked.
We mainly identified our html files (we have two files, located at the root of the folder, index.html and login.html). There are empty.
Other non js resources seems properly handled (i18n properties, manifest, ...)
If we target another directory (like the default `dist`) then these files are correctly handled.

## Conclusion
Everything behaves as if source and target folders can be the same folder, except that html files are not properly handled. Is it a bug ?

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `1.5.4`
- Node.js Version: `12.4.0`
- npm Version: `6.9.0`
- OS/Platform: `Windows 10`

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [X] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
@GuillaumedesPommareSAP please let us know if this is still an issue for you. I'll close this as wontfix for the time being.
