### ISSUE TITLE
UI5 cli to run tests in headless mode in console to support continuous integration

### ISSUE THREAD

**Issue by atul221282** [SAP/ui5-tooling#305]
## Expected Behavior
UI5 tooling allows running tests in the browser via command line. I expect it to run in headless mode also to support continuous integration

## Current Behavior
Currently, it runs tests in a browser given via command line

## Steps to reproduce the issue
No steps required for this

## Context
Support for continuous integration

## Affected components
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)

**Comment by RandomByte** [comment]
Support for direct test execution is not in the scope of UI5 Tooling. You might want to checkout [karma-ui5](https://github.com/SAP/karma-ui5/) which might offer the functionality you are looking for.

https://github.com/SAP/ui5-cli/pull/66 proposed a convenience "ui5 test" command, which would invoke karma internally. But there are currently no plans to implement this anytime soon.
