### ISSUE TITLE
Implement per-project settings configuration for UI5 Tooling modules

### ISSUE THREAD

**Issue by RandomByte** [SAP/ui5-tooling#313]
It should be possible to set per-project defaults for various CLI parameters. This should be possible in a `settings` section of a projects configuration (e.g. `ui5.yaml`). Most prominently setting a default server port.

Note that CLI parameters passed to a call will always take precedence over any configured settings.

From our current [Configuration](https://github.com/SAP/ui5-project/blob/master/README.md#project-configuration) documentation:  
> #### server (optional)
> - `settings` (not yet implemented)
>    - `port`: Project default server port; can be overwritten via CLI parameters

## Affected components *(if known)*
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [x] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [x] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by flovogt** [comment]
Implemented for server and builder modules. Therefore closing this enhancement request.
