### ISSUE TITLE
Enhancement: automatic Bump version

### ISSUE THREAD

**Issue by jberthe** [SAP/ui5-tooling#349]
Hi,
This is n enhancement request. 
It wuld be very nice to have during the build process an automated version generator.

In the manifest of the SAPUI5 application there is an attribute: 
`		"applicationVersion": {
			"version": "1.0.1"
		},`
We can look at thie link: [](https://threedots.tech/post/automatic-semantic-versioning-in-gitlab-ci/)

## Expected Behavior
During the build process with a sopecific parameter like :
 --version=DEV then the application version would be v1.1.0_Build<currDate>
 --version=PRD then the application version would be v1.1.x (where x is incremental)

## Current Behavior
None

## Affected components *(if known)*

- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
@mauriciolauffer is right, the `replaceVersion` task will replace any `${version}` placeholders with your projects version as defined in the package.json:

https://github.com/SAP/ui5-builder/blob/6d44481ad3668758d4c008d28b11cb47ca6bbee1/lib/tasks/replaceVersion.js#L21-L22

But I think @jberthe was looking for a solution to exclusively bump the version defined in manifest.json. https://www.npmjs.com/package/ui5-bump-version looks like a pretty good solution for that. And I think it makes sense to have a dedicated tool for this process.

I understand that the requirement for UI5 Tooling is therefore obsolete. So I'll close this issue. Thanks everyone!
