### ISSUE TITLE
Please document the default build tasks and their order

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP/ui5-tooling#352]
The default build tasks and their order result from https://github.com/SAP/ui5-builder/blob/master/lib/tasks/taskRepository.js in combination with https://github.com/SAP/ui5-builder/blob/master/lib/builder/builder.js and e.g. https://github.com/SAP/ui5-builder/blob/master/lib/types/library/LibraryBuilder.js.

IMHO the default build tasks and their order should be documented somewhere. Currently they can only deduced by examining these files.

**Comment by matz3** [comment]
Standard Tasks are now documented here: https://sap.github.io/ui5-tooling/pages/Builder/#standard-tasks
