### ISSUE TITLE
Exclude option in build configuration being ignored

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-tooling#358]
## Expected Behavior
Shall not include excluded resources in build.

## Current Behavior
Although excluded in [configuration](https://github.com/BenReim/openui5-sample-app/blob/bundle-conf/ui5.yaml), resource is still being considered during build process.

## Steps to reproduce the issue
1. Clone and checkout minimal sample project
`git clone -b bundle-conf https://github.com/BenReim/openui5-sample-app.git`

2. Run build
`npm install && ui5 build --a`

3. Watch build log output referring to excluded resource
`WARN lbt:bundle:Builder **** warning: module sap/ui/demo/todo/scripts/mockserver.js requires top level scope and can only be embedded as a string (requires 'eval')`

## Log Output / Stack Trace
```
> ui5 build --a
info builder:builder Building project openui5-sample-app including dependencies...
info builder:builder �   (1/1) Building project openui5-sample-app
info builder:builder application openui5-sample-app � (1/9) Running task escapeNonAsciiCharacters...
info builder:builder application openui5-sample-app � (2/9) Running task replaceCopyright...
info builder:builder application openui5-sample-app � (3/9) Running task replaceVersion...
info builder:builder application openui5-sample-app � (4/9) Running task generateFlexChangesBundle...
info builder:builder application openui5-sample-app � (5/9) Running task generateComponentPreload...
WARN lbt:bundle:Builder **** warning: module sap/ui/demo/todo/scripts/mockserver.js requires top level scope and can only be embedded as a string (requires 'eval')
info builder:builder application openui5-sample-app � (6/9) Running task generateBundle...
info builder:builder application openui5-sample-app � (7/9) Running task createDebugFiles...
info builder:builder application openui5-sample-app � (8/9) Running task uglify...
info builder:builder application openui5-sample-app � (9/9) Running task generateVersionInfo...
info builder:builder Build succeeded in 604 ms
info builder:builder Executing cleanup tasks...
```

**Comment by RandomByte** [comment]
Updated the documentation at https://sap.github.io/ui5-tooling/stable/pages/Configuration/#exclude-resources
