### ISSUE TITLE
Nested Component Projects: Component-preload.js files are not generated 

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-tooling#366]
## Expected Behavior
When running a preload-build, `Component-preload.js` files should be generated for each `Component.js` file within an ui5 app project.

## Current Behavior
In UI5 App Projects that contain component files, a `Component-preload.js` file is only generated for the root level Component.js files. For any other Component.js files that are placed in subfolders within the project, debug sources – yet no preload files - are currently being generated. This leads to 404 requests during runtime such as:

```
ui5loader-dbg.js GET https://**/Component-preload.js 404
```

## Steps to reproduce the issue
1. Clone the openui5-sample app

2. Within the `webapp` directory, create a sub folder and add a `Component.js` file and some basic content

3. Build the projects
` ui5 build --a`

4. A preload file has only been generated for the top-level Component.js file

## Affected components 
- [X] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
The issue can still be reproduced as described in [Benjamin's repository](https://github.com/SAP/ui5-tooling/issues/366#issuecomment-546869801)

@ThePlenkov I know your question is old, but here's the documentation on configuring preloads for subcomponents, including examples: https://sap.github.io/ui5-tooling/pages/Configuration/#component-preload-generation

**Comment by RandomByte** [comment]
Hey @BenReim, sorry for the delay. We just had another look at this issue and found that there is a mismatch in the component names that prevents this from working as expected.

The component at `webapp/routes/child1/Component.js` is missing the "routes" path segment in it's name:

```js
return UIComponent.extend("ui5lab.app.GeometryApp.child1.Component", {
``` 

After changing this to `ui5lab.app.GeometryApp.routes.child1.Component` and updating all other references, the loader will use the bundled resource from Component-preload.js as expected.

Note that our loader does not use the `resourceroots` mapping defined in the index.html for this kind of resolution. Therefore the component name must match the path in the bundle.
