### ISSUE TITLE
`ui5 build` command mistakenly minifies support rules

### ISSUE THREAD

**Issue by codeworrior** [SAP/ui5-tooling#376]
## Expected Behavior
After a full build, the support rule files (`*.support.js`) still should not be uglified to keep them readable in the editor of the UI5 Support Assistant. 

## Current Behavior
The `ui5 build` command also uglifies `*.support.js` files and creates `*.support-dbg.js` files for them. This differs from the official downloads.

## Steps to reproduce the issue
1. Build one of the OpenUI5 libraries with `ui5 build` and check the content of the output directory

## Context
- UI5 Module Version: `any`
- Node.js Version: `any`
- npm Version: `any`
- OS/Platform: all, except the "I-restore-support-files-after-minification" OS, version 4.2ff

## Affected components
- [x] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by flovogt** [comment]
This issue is fixed with UI5 Tooling V3. Therefore closing this issue.
