### ISSUE TITLE
Scaffolding

### ISSUE THREAD

**Issue by piejanssens** [SAP/ui5-tooling#40]
As of now, two critical tools from the WebIDE for basic development are missing from offline/local development using the ui5 tools through cli. Please correct me if I'm wrong...
- Deploying to ABAP https://github.com/SAP/ui5-tooling/issues/17
- Scaffolding for new projects

**Comment by Smux** [comment]
Is scaffolding on the roadmap?

**Comment by RandomByte** [comment]
>Is scaffolding on the roadmap?

@Smux [Yep](https://github.com/SAP/ui5-tooling/issues/101)

**Comment by jberthe** [comment]
> Is scaffolding on the roadmap?

Hello, I'm starting an npm module base on Yo to generate a UI5 project. 

Please feel free to contribute :
[https://github.com/jberthe/generator-app-fiori](https://github.com/jberthe/generator-app-fiori)

**Comment by piejanssens** [comment]
@RandomByte What about wrapping around https://www.npmjs.com/package/@sapui5/generator-sapui5-templates?

**Comment by RandomByte** [comment]
@piejanssens do you mean wrapping Yeoman or just reusing the content?

Afaik there are some changes planed for that package later this year or early next year, so in any way we should wait for that to happen.

**Comment by piejanssens** [comment]
Invoke `yo @sapui5/sapui5-templates` as part of `ui5 init` when the user wants to use a template.
There is also a lot of work put into https://github.com/SAP/generator-easy-ui5 by @IObert.
Ideally: `ui5 cli` adopts `easyui5`, which in turn incorporates `@sapui5/sapui5-templates`.

**Comment by IObert** [comment]
Hi @piejanssens,
it absolutely makes sense to reuse as much as possible for this task. We're already in contact to work together on this :)

**Comment by piejanssens** [comment]
Will @sapui5/generator-sapui5-templates also be deprecated in favor of @sap/generator-fiori?

@sap/generator-fiori-freestyle (deprecated)
@sap/generator-fiori-elements (deprecated)

**Comment by vobu** [comment]
i just wish they'd all bend the knee to @IObert's easy-ui5. Or cross the streams. Or take the vow. Whatever works to get rid of the closed-shop, self-forking templating hydra, so we could all just do
`yo easy-ui5`
leaving more time for 🍺 or  hugging 🌳 or whatever is more fun than working the next template generator out there.

**Comment by Friscas** [comment]
@vobu  i didn't know easy-ui5 was thing 😅 thank you very much 😀 I created a fork for ui5-cli and started adding the "create" [command](https://github.com/Friscas/ui5-cli/commit/9149e3d6691a12b06dd845068b3b9f5b8ca8b210) but I think I'm just wasting my time 😭

**Comment by vobu** [comment]
> @vobu i didn't know easy-ui5 was a thing 😅 thank you very much 😀 I created a fork for ui5-cli and started adding the "create" [command](https://github.com/Friscas/ui5-cli/commit/9149e3d6691a12b06dd845068b3b9f5b8ca8b210) but I think I'm just wasting my time 😭

i like the effort! and certainly not a waste of time per se - although @pmuessig, @RandomByte + @matz3 are currently in the processing of designing the command extensibility for the UI5-tooling CLI. You might want to wait until this is announced and available in order to bolt in your version of `ui5 create` :)

**Comment by vobu** [comment]
i'd like to ask @RandomByte to close this for now in favor of the current state of things:
- scaffolding for OpenUI5-based apps got some way with easy-ui5, especially with it now being a wrapper for all'em ui5-community generators (https://github.com/ui5-community?q=generator&type=&language=&sort=) as described in https://blogs.sap.com/2021/04/09/easy-ui5-3.0-from-community-contributions-to-community-plugins/
- there is and will be movement also related to fiori-tools, the "other" available generator/scaffolding solution in BTP
- command extensibility for `ui5-tooling` is definitely also a thing, providing the basis for custom commands such as the previously mentioned `ui5 create`
cheers, v.

**Comment by RandomByte** [comment]
Right, I think the community generators linked by @vobu should cover most aspects of this requirement. Integrating them one way or another into the UI5 CLI for convenience might be a topic in the future.

**Comment by pmuessig** [comment]
Just a heads up, you might have gotten someone else mixed up with my username, so they have no optics on your @ mention 🙂.

**Comment by codeworrior** [comment]
@pmuessig Thanks for pointing this out (and sorry for yet another spam). 

Adding @petermuessig instead.

**Comment by petermuessig** [comment]
@pmuessig - nice to meet you! 😄  - maybe we should discuss a GitHub username change - this is the only place where I do not own the @pmuessig handle - but honestly this would cause too much trouble... 

@vobu - yes, the command extensibility will allow to enable a reuse of the existing community generators also with the UI5 Tooling. As this is mainly convenience I would also keep that topic for the future.

**Comment by pmuessig** [comment]
@petermuessig  The most silly part is that I have a cousin (and grandfather) also named Peter... So yeah, I am sure we have all stepped on each others toes somewhere claiming that oft sought after username 

Anyways, it was very nice to meet you, I'm honored we share the same taste in something so trivial as username handles😄
