### ISSUE TITLE
Add support for credentials/env in @sap/ux-ui5-tooling - fiori-tools-proxy

### ISSUE THREAD

**Issue by sammok83** [SAP/ui5-tooling#460]
## Is your feature request related to a problem? Please describe.
No

## Describe the solution you'd like
@sap/ux-ui5-tooling - Connecting to a back-end system using fiori-tools-proxy. Can we add credentials (username/password) with env support please? This save time from entering the credentials again. Many custom middlewares already has this feature including my own.

**Comment by RandomByte** [comment]
Hi and thanks for reaching out!

Apparently, the `@sap/ux-ui5-tooling` module is not part of the UI5 Tooling project (our modules all start with `@ui5/*`). It is rather part of the SAP Fiori tools project, which is not open source as of today.

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-elements/tools-faq

Or by asking your questions on the extension's page: https://marketplace.visualstudio.com/items?itemName=SAPSE.sap-ux-fiori-tools-extension-pack&ssr=false#qna

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project.

*Related issue: https://github.com/SAP/ui5-tooling/issues/241#issuecomment-656683092*
