### ISSUE TITLE
option to transpile es6 code

### ISSUE THREAD

**Issue by karanjeet-singh-ub** [SAP/ui5-tooling#467]
following the documentation i could not find an option to transpile my app to es5 so that it works well on IE.
please convert to a feature request if this option is not available.

thank you!

**Comment by vobu** [comment]
https://github.com/petermuessig/ui5-ecosystem-showcase/tree/master/packages/ui5-task-transpile

**Comment by karanjeet-singh-ub** [comment]
@vobu yes i came across this module but was hoping to have this option available in @sap

**Comment by matz3** [comment]
Right now we don't plan to include tasks such as transpiling directly into UI5 Tooling.

As suggested by @vobu we recommend using custom tasks to transform sources.
