### ISSUE TITLE
ui5 cli does not create source maps

### ISSUE THREAD

**Issue by matzetronic** [SAP/ui5-tooling#472]
Hi,

we want to create a ui5 library using ui5 cli. The library is created including minified files and -dbg.js files but no source maps are created.

## Expected Behavior
A js.map file should be created for each source file and minified sources should have a source mapping url pointing to the not minified source (-dgb.js) files.

## Current Behavior
No source maps are created during "ui5 build".

## Steps to Reproduce the Issue
run "ui5 build" in a ui5 library and inspect the build result.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.6.6`**
 * Node.js Version: **`10.22.0`**
 * npm Version: `6.14.6`
 * OS/Platform: `Mac OS 10.15.7`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

**Comment by RandomByte** [comment]
Hi and thanks for opening this issue 👋

Generating source maps is on our internal backlog and the heavy work has already been done in
https://github.com/SAP/ui5-builder/pull/282.

However there are still some tricky questions on how to integrate this new build step in a well working and performant way. Also see https://github.com/SAP/ui5-builder/pull/282/files#r330896961

I am currently looking into refactoring parts of `@ui5/project` to improve the integration of such tasks. We hope to solve this soon as it also becomes critical for our internal switch of the production UI5 build to UI5 Tooling.

I'll leave this issue open so others can find it but I'll label it as a feature request 👍

**Comment by flovogt** [comment]
Fixed with https://github.com/SAP/ui5-builder/pull/695 and available as of [v3.0.0](https://github.com/SAP/ui5-cli/releases/tag/v3.0.0)
