### ISSUE TITLE
Feature request: layout editor

### ISSUE THREAD

**Issue by jvanattedev** [SAP/ui5-tooling#473]
I was wondering whether it would be possible to include the layout editor for XML Views. It is available in SAP WebIDE, in SAP Business Application Studio, but not yet in VS Code. I don't know if this is the package to include it; perhaps it could be offered separately. But in any case, the layout editor already exists and it would be very useful for developers.

A link to what I mean: https://developers.sap.com/tutorials/appstudio-fioriapps-create.html#b9cfceed-167d-4d7a-aae5-857e7390206b

**Comment by matz3** [comment]
Hey @jvanattedev

as you already guessed, this is not the right package to include such a XML view layout editor extension for VS Code.

I'd suggest to ask this question in the SAP Community for the SAP Business Application Studio:
https://answers.sap.com/tags/67837800100800007077
