### ISSUE TITLE
ERRORS: 'return' parse and outside of function on running "ui5 build --clean-dest"

### ISSUE THREAD

**Issue by zayidu** [SAP/ui5-tooling#476]
Hello Team,

I am getting the below error on running "ui5 build --clean-dest".

Stack Trace:
SyntaxError: 'return' outside of function
    at js_error (/Users/zayidu.ansari/Documents/ZayiduDevContents/ZZ_REPORT/node_modules/terser/dist/bundle.min.js:546:11)

Multiple errors like below:
ERR! lbt:resources:ResourcePool failed to parse 
/node_modules/@ui5/cli/node_modules/JSONStream/test/gen.js: Line 1: Illegal return statement

Can you please help me on this?

## Current Behavior
⚠️  Process Failed With Error

Error Message:
'return' outside of function

Stack Trace:
SyntaxError: 'return' outside of function

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: 14.15.3
 * npm Version: `unknown`
 * OS/Platform: Mac
 * 

## Log Output / Stack Trace

```
{...}
```

**Comment by matz3** [comment]
This sounds like a parsing error in one of the project files.
Can you provide the full log output? The filename should be visible in the log.

Please note that some new / experimental ECMA-Script features can't be used right now.
See https://github.com/SAP/ui5-tooling/issues/354 for more details on this.
