### ISSUE TITLE
replaceVersion task is always replacing the version with 1.0.0

### ISSUE THREAD

**Issue by braunadr** [SAP/ui5-tooling#485]
## Expected Behavior
I was expecting that I can use the replaceVersion task to do some versioning on my different releases. So when I have major or minor releases the version number should change accordingly. 

## Current Behavior
The version number gets always replaced with 1.0.0

## Steps to Reproduce the Issue
You just need to build any app and you will see in the dist folder that the version is still 1.0.0

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI):2.2.6
 * Node.js Version: 12.18.3
 * npm Version: 6.14.6
 * OS/Platform: Mac OS
 * Browser *(if relevant)*:-
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

manifest.json: 

"applicationVersion": {
			"version": "${version}"
		}
after replace version task in dist folder its always like that: 

"applicationVersion": {
			"version": "1.0.0"
		}

**Comment by RandomByte** [comment]
The default behavior of the `replaceVersion` task as used in UI5 Tooling is to take the version from a project's `package.json`.

Could you please check whether your projects `package.json` contains a section `"version": "1.0.0"`?

**Comment by braunadr** [comment]
ok got it but that would mean that there is no way to automate the versioning. I would need to change the version in the package.json file always manually right? Best case would be if it checks for example the commit message and depending on some keywords it would change the version accordingly.

**Comment by RandomByte** [comment]
I think it's rather the other way around. UI5 Tooling jumps onto the well established version management of npm here. And there are *a lot* of tools to manage the package version of an npm module.

For what you are describing, I think you are looking for a tool along the line of [semantic-release](https://github.com/semantic-release/semantic-release). There are also others.

In general: UI5 Tooling is decoupled from your projects dependency and version management. By default, it currently assumes you are working in an "npm environment". This means it looks for `package.json` files and parses the `name`, `version` and `dependencies` information in there to get things running. But it doesn't really care how this information is managed. That's a task for the package manager of your choice, being npm, Yarn, or some other tool.

**Comment by braunadr** [comment]
Alright thanks a lot for your fast help.
