### ISSUE TITLE
Builder - Add sap.cloud section in generateLibraryManifest

### ISSUE THREAD

**Issue by koemaeda** [SAP/ui5-tooling#491]
## Is your feature request related to a problem? Please describe.

I cannot use the `generateLibraryManifest` task to generate manifests for UI5 libraries deployed to SCP Cloud Foundry Portal, because the mandatory section `sap.cloud` is not supported.

## Describe the solution you'd like

I believe adding 2 new optional fields to the `.library` file, and mapping them to the `sap.cloud` section would be ideal.

## Describe alternatives you've considered

Generating the `manifest.json` in a build, copying it from `dist` and manually adding the `sap.cloud` section.

## Additional context

I'm using Builder for a UI5 library deployed to SCP Cloud Foundry Portal (managed Approuter).

The applications and libraries must be deployed to a `html5-apps-repo` service instance with the `sap.cloud.service` field present in their `manifest.json`.

From [SAP Help Portal - Expose HTML5 Applications in Portal](https://help.sap.com/viewer/ad4b9f0b14b0458cad9bd27bf435637d/Cloud/en-US/3a0e6d6b791c4c2189f6a0a424188362.html):

> To expose an HTML5 Application in SAP Cloud Platform Portal , you need to add some information to the manifest.json file.
> 
> Configuration | Mandatory? | Description
> -- | -- | --
> `sap.cloud.service` | Mandatory | Defines the business service.
> `semanticObject` and `action` | Mandatory | Defines the navigation intent, which is composed of a semantic object and the action that is performed on this object.

Obs: Although this is not documented, I've found that UI5 libraries don't need the `semanticObject` and `action` (it wouldn't make sense anyway).

This is what this section looks like:

```
"sap.cloud": {
  "public": true,
  "service": "my.example.service"
}
```

This is the current generated `manifest.json` in file [`manifestCreator.js`](https://github.com/SAP/ui5-builder/blob/master/lib/processors/manifestCreator.js#L690):

```javascript
	return {
		"_version": descriptorVersion.toString(),
		"sap.app": await createSapApp(),
		"sap.ui": createSapUi(),
		"sap.ui5": createSapUI5(),
		"sap.fiori": createSapFiori(),
		"sap.platform.abap": createSapPlatformABAP(),
		"sap.platform.hcp": createSapPlatformHCP()
	};
```

**Comment by RandomByte** [comment]
Hey, after discussing this in the team again, we decided to go ahead with a "manifest first" approach. This means our recommendation for libraries like yours is to create a static manifest.json and maintain the required section manually.

In the future, we might enhance UI5 Tooling with functionality to dynamically update existing manifest.json files during the build if necessary (@ecker see also internal ref CPOUI5FOUNDATION-295). But for the time being, no further efforts will go into the legacy .library format.

Please let us know if this causes great inconvenience to you. In that case we might reconsider other alternatives.
