### ISSUE TITLE
Error While using ui5 add command 

### ISSUE THREAD

**Issue by amitkrishna** [SAP/ui5-tooling#498]
## Expected Behavior
Unable to add a theme using  
'''
ui5 add sap.m themelib_sap_fiori_3 --verbose
'''

## Current Behavior
Unable to add theme 
getting an error 
⚠️  Process Failed With Error

Error Message:
[npm translator] Could not identify root project.

## Steps to Reproduce the Issue

ui5 add sap.m themelib_sap_fiori_3 --verbose
// in the directory
## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: `14.15.0`
 * npm Version: `6.14.6`
 * OS/Platform: Windows
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

⚠️  Process Failed With Error

Error Message:
[npm translator] Could not identify root project.

Stack Trace:
Error: [npm translator] Could not identify root project.

```
{...}
```

**Comment by RandomByte** [comment]
Hi Amit,

Thanks for reporting.

The error message "Could not identify root project" is typically an indicator that the `ui5` command has been executed in the wrong directory. You should executed it in the same directory as where your project's `package.json` and `ui5.yaml` reside.

Kindly double check your setup with our getting started guide: https://sap.github.io/ui5-tooling/pages/GettingStarted/#enabling-an-existing-project

Apparently I'm unable to reproduce your issue with the provided information. I tried the following:
1. Clone https://github.com/SAP/openui5-sample-app
2. In the openui5-sample-app directory, execute `npm install`
3. Execute `ui5 add sap.m themelib_sap_fiori_3`

This works as expected:
```
Updated configuration written to ui5.yaml
Added framework libraries sap.m themelib_sap_fiori_3 as dependencies
```

Please double check your setup as described above and report back if you are still experiencing this error.
