### ISSUE TITLE
ui5 serve error message is misleading

### ISSUE THREAD

**Issue by svbender** [SAP/ui5-tooling#50]
## Expected Behavior
If i start the ui5 server in a directory without a valid ui5.yaml file, it can't be served and I expect a meaningful error message like git does:
`fatal: Not a git repository (or any of the parent directories): .git`

## Current Behavior
The current error message is misleading and it seems that the ui5 tooling has an issue:
```
Error: Failed to configure root project "openui5". Please check verbose log for details.
    at configPromises.push.configureProject.then ([...]\ui5-cli\node_modules\@ui5\project\lib\projectPreprocessor.js:66:13)
```
## Steps to reproduce the issue
1. open a console window
2. Navigate into a directory without ui5.yaml (e.g. root directory of openui5)
3. start the server with `ui5 serve`

## Context
- OS/Platform: ALL
- Node.js Version: ALL
- npm Version: ALL
- Browser *(if relevant)*:  ALL
- Other information: -

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [x] [ui5-server](https://github.com/SAP/ui5-server)
- [x] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

**Comment by RandomByte** [comment]
Fixed in current master. If a project is missing a ui5.yaml we now display an error like this:

`Failed to read configuration for project my-project at "/path/to/my-project/ui5.yaml". Error: ENOENT: no such file or directory, open '/path/to/my-project/ui5.yaml'`
