### ISSUE TITLE
Testsuite support

### ISSUE THREAD

**Issue by DenisTis** [SAP/ui5-tooling#504]
Dear UI5 Team,

thanks for your work. This is a very handy module, which I use since half a year and I am very happy with it.
I recently needed to enhance my projects with testing (though still not sure, if unit tests or opa tests would be used). Then I checked first if your module supports it.

For sure, I can use other js modules for that, but I think it would be cool if you would deliver testsuite in your module, which would be run during build before preloading to server. 

What is your vision on it?

**Comment by RandomByte** [comment]
Hey, Thank you for that question. For general information on testing in UI5, please checkout the documentation in the Demo Kit: https://ui5.sap.com/#/topic/7cdee404cac441888539ed7bfe076e57

You can also take a look at the [openui5-sample-app](https://github.com/SAP/openui5-sample-app), which represents current best practices on testing UI5 applications. It makes use of [karma-ui5](https://github.com/SAP/karma-ui5/) as a test runner.

UI5 Tooling itself does not provide any testing capabilities and nothing is planned in that direction. However, karma-ui5 can internally facilitate the ui5-server module to run a project's tests.
