### ISSUE TITLE
I18n Editing Issue

### ISSUE THREAD

**Issue by daniel-cabral** [SAP/ui5-tooling#508]
When UI5 Server is running and you want to edit any i18n, you can't type spaces - copy/paste is possible. Each character typed triggers live reload.

I've disabled any other possible extension that could cause interference but found this pattern: only when the ui5 server is running.

Using the latest VSCode and ui5 tooling at this date.

Edit: Found the agressor extension: SAP Fiori tools - XML Annotation Language Server

**Comment by matz3** [comment]
> Edit: Found the agressor extension: SAP Fiori tools - XML Annotation Language Server

Looks like you already found the related extension, right?
As the SAP Fiori tools are not part of this project, I'm closing the issue.

Please use the mentioned support channel of the extension as described here: https://marketplace.visualstudio.com/items?itemName=SAPSE.sap-ux-annotation-modeler-extension

**Comment by daniel-cabral** [comment]
Hi @matz3 ! Thanks for your attention. I've already reported there.
