### ISSUE TITLE
ui5 build generates preload file with Syntax error

### ISSUE THREAD

**Issue by simonroloff** [SAP/ui5-tooling#514]
# Expected Behavior
building my sapui5 app should produce valid Component-preload.js file

# Current Behavior
building my app produces duplicate variable declarations which makes the Component-preload.js useless.

# Steps to reproduce the issue
1. `git clone https://github.com/simonroloff/ui5tooling.git`
2. `cd ui5tooling`
3. `npm install @ui5/cli`
4. `ui5 build` => no error, no warning. Everything fine.
5. `npm i -g eslint`
6. Check the generated preload file with eslint `eslint ./dist/Component-preload.js` => Parsing error: Identifier 'r' has already been declared

**Comment by matz3** [comment]
Thanks for reporting this.
I was able to isolate this issue by just using terser (which we use to minify JS code) and eslint directly:
```sh
npm i -g terser
npm i -g eslint
terser --mangle -- webapp/Component.js | eslint --stdin
```
```
<text>
  1:1441  error  Parsing error: Identifier 'r' has already been declared

✖ 1 problem (1 error, 0 warnings)
```

So I assume this to be an issue with terser not producing valid JavaScript or a parsing error within ESLint.
Either way, it can't be solved by us directly.
Therefore I'd suggest you to further analyze this case to file an issue in the respective project.

**Comment by codeworrior** [comment]
I would say it's a terser issue. Name mangling creates:

```js
	let o, r;

	function r(e) {
	...

        function a(e) {
                ...
	        for (r = 0; r < t.length; r++) {

```

which obviously causes a conflict for 'r'. Maybe terser decides for a short name only based on the usages (only inside function 'a') and misses to take the place of the declaration into account. Moving variables `oFile` and `z` in your original source code into the scope where they are used, fixes the parsing problem for me.

**Comment by simonroloff** [comment]
Thank you for analysing my issue. I will file this issue in the terser project.
@codeworrior : thanks, we also moved the variables in the original source code as a workaround.
