### ISSUE TITLE
How to integrate External node modules in UI5

### ISSUE THREAD

**Issue by t5ar** [SAP/ui5-tooling#519]

**Comment by codeworrior** [comment]
Documentation is rare, but the ui5-community project [ui5-library-showcase](https://github.com/ui5-community/ui5-library-showcase/tree/main/packages/ui5-library-showcase) shows an example how to do that (dependency `@zxing/library` is used in module [QRCodeRenderer.js](https://github.com/ui5-community/ui5-library-showcase/blob/main/packages/ui5-library-showcase/src/ui5/community/showcaselib/QRCodeRenderer.js)).

**Comment by svbender** [comment]
It is possible with shims, please have a look at the documentation:
https://sap.github.io/ui5-tooling/pages/extensibility/ProjectShims/

You can also check this blog post:
https://blogs.sap.com/2017/04/30/how-to-include-third-party-libraries-modules-in-sapui5/

**Comment by matz3** [comment]
Another example was part of last years UI5con session "UI5 Tooling 2020". Slides, Recording and Code can be found here:
https://github.com/matz3/ui5con20-ui5-tooling
