### ISSUE TITLE
Custom task doesn't replace existing i18n file

### ISSUE THREAD

**Issue by Yunustuzun** [SAP/ui5-tooling#520]
## Expected Behavior
Change i18n files according to the **workspace.write** command

## Current Behavior
Do not write resources to i18n files according to the **workspace.write** command

## Steps to Reproduce the Issue
- run npm command "ui5 build --verbose --exclude-task escapeNonAsciiCharacters"
- Everything working well except of the **await workspace.write** 
- Repository link https://github.com/Yunustuzun/UI5-i18n-cleaner
## Context

```yaml
builder:
  customTasks:
    - name: cleanUnusedi18nKeys
      beforeTask: replaceCopyright

---
# Task extension as part of your project
specVersion: "2.1"
kind: extension
type: task
metadata:
  name: cleanUnusedi18nKeys
task:
  path: tasks/cleanUnusedi18nKeys.js
```
``` 
module.exports = async function ({ workspace, dependencies, taskUtil, options }) {
    // [...]


    const textResources = await workspace.byGlob("**/*{view.xml,fragment.xml,controller.js,manifest.json}");
    const i18nFiles = await workspace.byGlob("**/*.properties");
    var lines = [], line = {}, i18nString = "";

    // for (var i = 0; i < i18nFiles.length; i++) {

    await Promise.all(i18nFiles.map(async (i18nFile) => {
        // var i18nFile = i18nFiles[i];

        let i18nFileString = await i18nFile.getString();

        var i18nLines = i18nFileString.split(/\r?\n/);

        for (let i = 0; i < i18nLines.length; i++) {
            line = {};
            const i18nLine = i18nLines[i];

            var keyValue = i18nLine.split("=");
            if (keyValue.length < 1) {
                continue;
            }
            line.key = keyValue[0];
            line.value = keyValue[1];
            lines.push(line);
        }


        for (let i = 0; i < textResources.length; i++) {
            var textResource = textResources[i];
            let text = await textResource.getString();
            for (var k = 0; k < lines.length; k++) {
                line = lines[k];
                var searchReturn = text.search(line.key)
                if (searchReturn !== -1) {
                    lines[k].found = true;
                }
            }
        }

        lines = lines.filter((l) => l.found === true)


        for (let i = 0; i < lines.length; i++) {
            line = lines[i];
            i18nString += line.key + " = " + line.value + "\n";
        }

        await i18nFile.setString(i18nString)

        await i18nFile.getString(i18nString).then((text) => console.log(text));

        await workspace.write(i18nFile, { readOnly: true }).then(() => console.log('DONE'));

    }
    ));
```
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.10.3`**
 * Node.js Version: **`12.13.0`**
 * npm Version: `6.14.11`
## Log Output / Stack Trace
info builder:builder application UI5_TEMPLATE � (1/8) Running task cleanUnusedi18nKeys...
verb resources:tracing:Trace:globs [Trace: **/*{view.xml,fragment.xml,controller.js,manifest.json}
verb resources:tracing:Trace:globs   17 ms elapsed time
verb resources:tracing:Trace:globs   1 glob executions
verb resources:tracing:Trace:globs   2 reader-collections involed:
verb resources:tracing:Trace:globs       1x source of UI5_TEMPLATE
verb resources:tracing:Trace:globs       1x UI5_TEMPLATE
verb resources:tracing:Trace:globs ======================]
verb resources:tracing:Trace:globs [Trace: **/*.properties
verb resources:tracing:Trace:globs   2.84 ms elapsed time
verb resources:tracing:Trace:globs   1 glob executions
verb resources:tracing:Trace:globs   2 reader-collections involed:
verb resources:tracing:Trace:globs       1x source of UI5_TEMPLATE
verb resources:tracing:Trace:globs       1x UI5_TEMPLATE
verb resources:tracing:Trace:globs ======================]
appTitle = Route Management and Planner tracing:Trace:globs [Trace: **/*.properties
appDescription = Route Management and Planner
planner =  Planner
tours = Tours
locations = Locations
fleet = Fleet
openDocuments = Open Documents
 = undefined

verb resources:adapters:Memory Writing to virtual path /resources/int/ui5/template/i18n/i18n.properties
DONE
info builder:builder application UI5_TEMPLATE � (2/8) Running task replaceCopyright...

**Comment by RandomByte** [comment]
> Everything working well except of the await workspace.write

Could you please add some more details on the issue you are facing with the `workspace.write` API?

I can see that the modified i18n file is correctly written to `dist` and even included in the `Component-preload.js`. Was are you missing exactly? Thanks!

**Comment by Yunustuzun** [comment]
I waited to reflect changes inside webapp folder, not dist. I just realized it. Thanks for your reply. I closed the issue.
