### ISSUE TITLE
 unable to create a Fiori elements project with yeoman generator

### ISSUE THREAD

**Issue by balajimurugesan2016** [SAP/ui5-tooling#522]
I'm unable to create a Fiori elements project with yeoman generator. Please find the steps and error below

This happens with a SAP CAP project which is already created and deployed with few UI projects in it

app balaji$ yo
? 'Allo i340782! What would you like to do? @sap/fiori

Make sure you are in the directory you want to scaffold into.
This generator can also be run with: yo @sap/fiori

? Application Type SAP Fiori elements
? Which floorplan do you want to use?
List Report Object Page
? Data source Use a Local CAP Project
? CAP project folder path /Users/balaji/Projects/kpi-dashboard-ui
(node:25581) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
(Use node --trace-warnings ... to show where the warning was created)
(node:25581) Warning: Accessing non-existent property 'INVALID_ALT_NUMBER' of module exports inside circular dependency
? OData service kpiService
? Main entity EnablementSessions
? Module name enablementsessions
? Application title Manage Enablement Sessions
? Application namespace es
? Description Manage Enablement Sessions
? Add deployment configuration to MTA project (/Users/balaji/Projects/kpi
-dashboard-ui/mta.yaml) Yes
? Add FLP configuration Yes
? Configure advanced options No

 _-----_     ╭───────────────────────╮
|       |    │      Bye from us!     │
|--(o)--|    │       Chat soon.      │
---------´ │ Yeoman team │ ( _´U_ ) │ http://yeoman.io │
/A\ /╰───────────────────────╯
| ~ |
'..'_
´ |° ´ Y

**events.js:292
throw er; // Unhandled 'error' event
^

Error: spawn /usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/bin/mta ENOENT
at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
at onErrorNT (internal/child_process.js:465:16)
at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on Generator instance at:
at Immediate. (/usr/local/lib/node_modules/@sap/generator-fiori/node_modules/yeoman-generator/lib/index.js:791:20)
at processImmediate (internal/timers.js:461:21) {
errno: -2,
code: 'ENOENT',
syscall: 'spawn /usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/bin/mta',
path: '/usr/local/lib/node_modules/@sap/generator-fiori/generators/deployment-generator/deploy/bin/mta',
spawnargs: [
'get',
'resources',
'-p',
'/Users/balaji/Projects/kpi-dashboard-ui/mta.yaml'
]
}**

Kindly rectify this issue

**Comment by matz3** [comment]
I'm sorry, but I don't think that this is the right project to report this issue.

The package seems to be [@sap/generator-fiori](https://www.npmjs.com/package/@sap/generator-fiori) which contains a "Support" section in the README that describes how to obtain support and report issues.
