### ISSUE TITLE
UI5 deploy target shows info instead of warning

### ISSUE THREAD

**Issue by ianquigley-sap** [SAP/ui5-tooling#532]
## Expected Behavior
Deploying with UI5 CLI when no navigation inbound is defined, should be displayed as a `warning` rather than `info`. 

## Current Behavior

An info message is displayed to the user when no inbound navigation is found during ABAP deployment.

## Steps to Reproduce the Issue

1. Generate an application with missing Fiori launchpad configuration (FLP)
2. Deploy the application
3. An `info` message is displayed as follows:

![image](https://user-images.githubusercontent.com/15449680/124495879-95ac1f00-ddb0-11eb-9e71-dfd785b79e73.png)

This previously was a warning message.  Can it be reverted to a warning?

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`@2.11.3`**
 * Node.js Version: **`14.17.0`**
 * npm Version: `6.14.13`
 * OS/Platform: `Business Application Studio`
 * Browser *(if relevant)*: `N/A`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by svbender** [comment]
Hi and thanks for reaching out!

The custom task `deploy-to-abap` is part of the `@sap/ux-ui5-tooling` module which is not part of the UI5 Tooling project (our modules all start with `@ui5/*`). It is rather part of the SAP Fiori tools project, which is not open source as of today.

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

Or by asking your questions on the extension's page: https://marketplace.visualstudio.com/items?itemName=SAPSE.sap-ux-fiori-tools-extension-pack&ssr=false#qna

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project.
