### ISSUE TITLE
Help with server middleware for passportjs

### ISSUE THREAD

**Issue by uxkjaer** [SAP/ui5-tooling#544]
I'm trying to build a server middleware that leverages passport strategies to authenticate. I've got a basic express app running that can authenticate a user using a custom strategy. However I can't figure out how to use this with the server middleware functionality without spinning up a new express app.

Normally you would use app.use(passport.initialize()) and app.use(passport.session()) to help with injection the passport authentication. But as far as I can see, it's only the mountpath of my extension that is handled by app.use of the server.

Would it be possible to inject passport into the server to then use strategies to help with authentication?

**Comment by matz3** [comment]
Both, the default mountPath and the express default paths are `/`, which should behave the same as when you would call `app.use(fn)` without giving a path.

I think the only speciality is that you want to use two middleware functions within the custom middleware.
For that you can use the [router](https://www.npmjs.com/package/router) module to which you can register your middlewares (via `.use()`) and then return as the custom middleware function.
