### ISSUE TITLE
Enable `includePrerelease` for supporting EAP/nightly Node.js builds

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#550]
I'm on Node.js Canary (v17.0.0-v8-canary202108258414d1aed8) and when I run the `ui5 init`, I get an error.

## Expected Behavior
`ui5 init` should work, since  @ui5/cli requires >= 10

## Current Behavior
You are using an unsupported version of Node.js
Detected version v17.0.0-v8-canary202108258414d1aed8 but @ui5/cli requires >= 10

=> Please upgrade to a supported version of Node.js to use this tool

## Steps to Reproduce the Issue
1. Download and install https://nodejs.org/download/v8-canary/v17.0.0-v8-canary202108258414d1aed8/node-v17.0.0-v8-canary202108258414d1aed8-x64.msi
2. Install `@ui5/cli": "^2.12.1` as a dev dependency.
3. Run `ui5 init`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.12.1`**
 * Node.js Version: **`v17.0.0-v8-canary202108258414d1aed8`**
 * npm Version: `7.21.1`
 * OS/Platform: `Windows 10 21H1 x64`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

P.S. Yes, I know it's a canary/nightly/EAP version of Node.js, but still «@ui5/cli requires >= 10» means for me a support of v.17 as well,  maximum with crashes and errors, but still. I assume the current error is a matter of an implementation of a version number detection.

**Comment by codeworrior** [comment]
There's no magic behind `@ui5/cli`'s version check. It feeds the `process.version` and the `engines.node` range from its own package.json file into `semver`'s `satisfies` method:

```js
  server.satisfies("v17.0.0-v8-canary202108258414d1aed8", ">=10")
```

According to https://github.com/npm/node-semver#prerelease-tags , this returns false as the range does not explicitly allow pre-release versions.

We'll discuss whether we feel comfortable with setting the `includePrerelease` flag.

**Comment by pubmikeb** [comment]
Support of `includePrerelease` sounds great!
Maximum, UI5 Tools can raise a warning «pre-relese detected, no warranty at all»…

**Comment by matz3** [comment]
I'd be okay with enabling `includePrerelease`. I don't see a reason not allowing to use those versions. This also enables us to test new versions early to detect incompatibilities.
But an additional warning/hint as suggested by @pubmikeb should be logged to state that the version is not "supported" and issues could appear.
