### ISSUE TITLE
Upload canceled, archive could not be read or appears to be empty

### ISSUE THREAD

**Issue by sanjoy0308** [SAP/ui5-tooling#554]
I am running npm run deploy ("deploy": "ui5 build preload --clean-dest --config ui5-deploy.yaml --include-task=generateManifestBundle generateCachebusterInfo && rimraf archive.zip")

I get this error:

info builder:custom deploy-to-abap Create Archive
info builder:custom deploy-to-abap Starting Deployment.on com.asml.prodengapp 🔨 (11/11) Running task deploy-to-abap...
info builder:custom deploy-to-abap er:builder application com.asml.prodengapp 🔨 (11/11) Running task deploy-to-abap...
info builder:custom deploy-to-abap Using system [Temp System] from System store
Filtering system with ID [http://xxxxx.com] as it seems corrupt. Run repair
Filtering system with ID [https://xxxxx.com] as it seems corrupt. Run repair
Filtering system with ID [https://xxxxx:8300] as it seems corrupt. Run repair
ERR! builder:custom deploy-to-abap Request failed with status code 400dengapp 🔨 (11/11) Running task deploy-to-abap...
ERR! builder:custom deploy-to-abap SAPUI5 application  was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap SAPUI5 application  was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in regular mode, brief log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Upload canceled, archive could not be read or appears to be empty.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap SAPUI5 application  was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction: For backend administrators: use ADT feed reader "SAP Gateway Error Log" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
ERR! builder:custom deploy-to-abap Deployment Failed.
ERR! builder:custom deploy-to-abap SAPUI5 application  was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap SAPUI5 application  was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap ***** Upload of SAPUI5 App or Library from ZIP-Archive into SAPUI5 ABAP Repository *****
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Running in regular mode, brief log
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap Upload canceled, archive could not be read or appears to be empty.
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap SAPUI5 application  was not uploaded or registered successfully
ERR! builder:custom deploy-to-abap
ERR! builder:custom deploy-to-abap * Done *
ERR! builder:custom deploy-to-abap SAP_Transaction: For backend administrators: use ADT feed reader "SAP Gateway Error Log" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
info builder:builder Build succeeded in 4.31 s
info builder:builder Executing cleanup tasks...

**Comment by RandomByte** [comment]
Hi and thanks for reaching out!

The custom task `deploy-to-abap` is part of the `@sap/ux-ui5-tooling` module which is not part of the UI5 Tooling project (our modules all start with `@ui5/*`). It is rather part of the SAP Fiori tools project, which is not open source as of today.

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

Or by asking your questions on the extension's page: https://marketplace.visualstudio.com/items?itemName=SAPSE.sap-ux-fiori-tools-extension-pack&ssr=false#qna

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project. Also see https://github.com/SAP/ui5-tooling/issues/532#issuecomment-874580387 and https://github.com/SAP/ui5-tooling/issues/418#issuecomment-669189877
