### ISSUE TITLE
self-contained support for manifest.json

### ISSUE THREAD

**Issue by hschaefer123** [SAP/ui5-tooling#56]
## Expected Behavior
Using declarative objects like routing or models declared inside manifest.json,
it seems that they are currently not parsed

## Current Behavior
self-contained app requests such controls/libs/etc via custom request

## Steps to reproduce the issue
add routing to manifest.json for example router section with sap.m.roting.Router

## Affected components
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)

## Workaround
Inside Component.js add missing dependencies like
"sap/m/routing/Router"
to take care into build

**Comment by matz3** [comment]
`sap.ui5/models` should be detected.
`sap.ui5/routing` has been fixed with https://github.com/SAP/ui5-builder/pull/124 (part of `@ui5/cli` v0.2.9).

Handling for `sap.ui5/resources` is not that easy as those are not UI5 modules.

Anything missing for your use case?

**Comment by hschaefer123** [comment]
Hi Matthias,
first of all thanks to adding this and congrats to version 1.0.0 for the whole team especially to @RandomByte and you @matz3 .

I think, it has come to the right time to try the tooling with our OpenUI5 bonvendo ecommerce solution,
which will use three parts
- bontheme (but we still have to solve the issue with including the darkmode belize css stuff!) 
- boncore (shared reuse library) with custom controls
- boneco (the ecommerce app itself)

This year we will have some big developments on top of this so that would be a great test to see everything is working as expected!

Concerning bontheme it would be great, if you would find some mins to help to solver the current issues concerning referencing the npm packages while beeing able to compile/include the dark theme depenend css stuff.

Since we decoupled most of the dependencies from our solutions i will let you know what is currently missing in the tools.

Thanks you and regards
Holger

**Comment by matz3** [comment]
Do you mind [creating an issue](https://github.com/SAP/ui5-builder/issues/new) for the theme build problem in the ui5-builder repo?

I will follow-up there and close this issue.
