### ISSUE TITLE
UI5 builder doesn't replace `i18n` binding in `manifest.json` app descriptor

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#562]
In the `manifest.json` app descriptor I'm using a `i18n` binding, just like described in [Step 10: Descriptor for Applications](https://openui5nightly.hana.ondemand.com/topic/8f93bf2b2b13402e9f035128ce8b495f):

```json
"description": "{{APP_DESCRIPTION}}",
"i18n": {
	"bundleName": "com.app.i18n.i18n",
	"fallbackLocale": "en",
	"supportedLocales": [
		"en"
	]
},
"subTitle": "{{APP_SUBTITLE}}",
"tags": {
	"keywords": [
		"{{APP_TAGS_KEYWORD_01}}",
		"{{APP_TAGS_KEYWORD_02}}",
		"{{APP_TAGS_KEYWORD_03}}"
	]
},
```

Then I run `ui5 build`.

## Expected Behavior
`{{APP_DESCRIPTION}}`, `{{APP_SUBTITLE}}` etc. will be replaced with the values from the `i18n`-bundle.

## Current Behavior
`{{APP_DESCRIPTION}}`, `{{APP_SUBTITLE}}` etc. remain untouched.

## Steps to Reproduce the Issue
1. Define `manifest.json` with `{{APP_DESCRIPTION}}`, `{{APP_SUBTITLE}}`.
2. Run `ui5 build`.

## Context
 * UI5 Module Version: **`"@ui5/cli": "^2.12.1"`**
 * Node.js Version: **`16.9.1`**
 * npm Version: `7.23.0`
 * OS/Platform: `Windows 10 21H1 x64`

**Comment by codeworrior** [comment]
I'm sorry, but this is not a valid use case from our POV. 

The purpose of the placeholders is to allow translation at runtime. It therefore doesn't make sense to do a replacement at build time.
