### ISSUE TITLE
Support for Fiori Launchpad Plugin Applications

### ISSUE THREAD

**Issue by javacplus** [SAP/ui5-tooling#564]
## Is your feature request related to a problem? Please describe.
Yes. I was trying to use ui5 build with "SAP LaunchPad Extension Plugin" application but it failed since there is no webapp folder

## Describe the solution you'd like
Add support to build SAP LaunchPad Plugin application using the tool

## Describe alternatives you've considered
Continue using SAP WebIDE

## Additional context
$ ui5 init --verbose
verb cli:middlewares:base using @ui5/cli version 2.12.1 (from 
\npm\node_modules\@ui5\cli\bin\ui5.js)
verb cli:middlewares:base using node version v14.17.1

⚠️  Process Failed With Error

Error Message:
Could not detect project type: **Could not find 'webapp' or 'src' / 'test' folders.**
Applications should only have a 'webapp' folder.
Libraries should only have a 'src' and (optional) 'test' folder.

Stack Trace:
Error: Could not detect project type: Could not find 'webapp' or 'src' / 'test' folders.
Applications should only have a 'webapp' folder.
Libraries should only have a 'src' and (optional) 'test' folder.
    at getProjectType (\npm\node_modules\@ui5\cli\lib\init\init.js:54:8)
    at Object.init (\npm\node_modules\@ui5\cli\lib\init\init.js:91:23)
    at async Object.initCommand.handler (\npm\node_modules\@ui5\cli\lib\cli\commands\init.js:22:24)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose

**Comment by RandomByte** [comment]
It seems that this "SAP LaunchPad Extension Plugin" application does not follow the common pattern of having a `webapp/` directory. In that case you need to configure the directory containing the application sources in the `ui5.yaml` as described here: https://sap.github.io/ui5-tooling/pages/Configuration/#path-mapping

You might also consider reaching out to the Web IDE community on how to migrate such projects to UI5 Tooling: https://community.sap.com/topics/web-ide
