### ISSUE TITLE
Minifying UI5 HTML-bootstrap file

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#571]
When running all UI5 Tooling tasks I get a minified `Component-preload.js` which is OK but the UI5 HTML-bootstrap file remains untouched.

Is it possible to minify an UI5 HTML-bootstrap file with UI5 tooling?

**Comment by matz3** [comment]
Currently that's not part of our feature-set, but there's a custom task that seems to cover this requirement: https://github.com/mauriciolauffer/ui5-task-minifier

Apart from that, you can also create your own custom tasks: https://sap.github.io/ui5-tooling/pages/extensibility/CustomTasks/
