### ISSUE TITLE
ui5 init ⚠️  Process Failed With Error

### ISSUE THREAD

**Issue by vikash8859** [SAP/ui5-tooling#573]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by matz3** [comment]
Closing as there was no further response from the author within 3 weeks
