### ISSUE TITLE
"AttachmentService" reuse component is not supported

### ISSUE THREAD

**Issue by babyboyface** [SAP/ui5-tooling#577]
## Expected Behavior
{UI5 tooling should support attachment service reuse component as normal UI5 library}

## Current Behavior
{Attachment service reuse component is not supported.
Error Message:
Resolution of framework libraries failed with errors:
Failed to resolve library sap.se.mi.plm.lib.attachmentservice: Could not find library "sap.se.mi.plm.lib.attachmentservice"}

## Steps to Reproduce the Issue
1. {Add "- name: sap.se.mi.plm.lib.attachmentservice" to UI5.yaml}
2. {Start UI5 server}
3. {Got the error "Resolution of framework libraries failed with errors:
Failed to resolve library sap.se.mi.plm.lib.attachmentservice: Could not find library "sap.se.mi.plm.lib.attachmentservice"}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): 2.14.0
 * Node.js Version: v16.10.0
 * npm Version: `8.1.0`
 * OS/Platform: `windows`
 * Browser *(if relevant)*: `chrome`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{Error Message:
Resolution of framework libraries failed with errors:
Failed to resolve library sap.se.mi.plm.lib.attachmentservice: Could not find library "sap.se.mi.plm.lib.attachmentservice"}
```

**Comment by RandomByte** [comment]
Hi @babyboyface,

`sap.se.mi.plm.lib.attachmentservice` is apparently not a standard library of the UI5 Framework. For example, it does not appear in the UI5 API Reference: https://ui5.sap.com/#/api

Therefore it is deemed a "project dependency" which needs to be managed differently. You would typically declare it in your project's `package.json` and install or link it using `npm`. Please also refer to our documentation at https://sap.github.io/ui5-tooling/pages/Overview/#project-dependencies
