### ISSUE TITLE
How to run Index.html directly on port without adding "/index.html"

### ISSUE THREAD

**Issue by nishan-nainsukha** [SAP/ui5-tooling#579]
My requirement is run index.html directly on the port like **localhost:3000** 
for this I tried to run via command  **"ui5 serve -o index.html"** but this is serving like  **localhost:3000/index.html** 
I also tried to configure the Resource path as index.html in ui5.yaml file but still the same result every time it adding the "/index.html" with the base URL.

can you please help me out for this issue.

**Comment by codeworrior** [comment]
Not sure if I got your requirement. Would you like to start the server and let the tooling open a browser at the root URL of the server, e.g.

```url
   http://localhost:3000
```
If so, then

```sh
  ui5 serve --open ""
```

should do the trick.

**Comment by nishan-nainsukha** [comment]
no this is also adding  "/index.html" after the URL    http://localhost:3000 --> http://localhost:3000 /index.html
my requirement is run index.html directly on http://localhost:3000  
without adding any extra words after port

**Comment by codeworrior** [comment]
For me it doesn't. 

Using
```
ui5 serve --open ""
```
(cli version 2.14.0) starts the server, opens the browser and shows the root URL. By looking at `window.location.href` in the browser window, I made sure that I'm not fooled by some URL beautification of the browser. It says `"http://localhost:8080/"` as expected.

Looking at the source of the serve command, this is reasonable:
```js
	if (argv.open !== undefined) {
		if (typeof argv.open === "string") {
			let relPath = argv.open || "/";
			if (!relPath.startsWith("/")) {
				relPath = "/" + relPath;
			}
			browserUrl += relPath;
		}
		const open = require("open");
		open(browserUrl, {url: true});
	}
```

It only adds whatever you give as argument.

Did you revert your yaml config that changes the resources path? Or did you configure additional middlewares that might do a redirect to a welcome page?

Last but not least, what OS platform are you on? The npm "open" module relies on some native functionality, so its behavior might differ between platforms (I'm on macOS 11.6).

**Comment by vobu** [comment]
you want this: https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/ui5-middleware-index

**Comment by nishan-nainsukha** [comment]
yes its working.
@vobu thanks

**Comment by codeworrior** [comment]
Ok, now I understand what you wanted to achieve. But still I don't get what component actively added index.html to the URL. That shouldn't be the case (and doesn't happen for me).
