### ISSUE TITLE
Please document what a custom task should do to abort the whole build

### ISSUE THREAD

**Issue by DerGuteWolf** [SAP/ui5-tooling#580]
We use several custom tasks in our builds and the last step is to deploy to our onpremise netweaver system. For this to happen we want to make sure our custom tasks which ran before were succesful.

Unfortunatly https://sap.github.io/ui5-tooling/pages/extensibility/CustomTasks/  does not indicate clearly what a custom task should do in order to abort the whole build because a fatal error happened.

Could you add a line on this docu page what a custom tasks should do best in order to abort the whole build?

**Comment by RandomByte** [comment]
Thanks for the input. A rejected promise should be sufficient. I'll update the documentation to add that info.
