### ISSUE TITLE
Themes of custom library dependency are not being build 

### ISSUE THREAD

**Issue by BenReim** [SAP/ui5-tooling#582]
## Expected Behavior
`library.sources.less` theme files of a custom library dependency should be build

## Current Behavior
The build result only contains the raw `library.sources.less` sources. 

## Steps to reproduce the issue
1. Clone library showcase repository
```shell
git clone https://github.com/ui5-community/ui5-library-showcase`
```

2. Build the app ( _including its project dependencies_ )
```shell
cd packages/ui5-app/ && yarn run build
```

3. Check themes folder in `dist` - css files have no been generated
```shell
$ ls dist/resources/ui5/community/showcaselib/themes/sap_fiori_3
library.source.less
```

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.10`**

## Log Output / Stack Trace

```
{...}
```

**Comment by matz3** [comment]
This seems related to https://github.com/SAP/ui5-tooling/issues/392

The themes are not built, as no `.library` file is available. I thought that we would have changed this to also check for `library.js` files (like we do for generating library-preload files), but it seems that's still not the case.
```
verb builder:tasks:buildThemes Filtering themes to be built:
verb builder:tasks:buildThemes Available libraries: /resources/sap/m/, /resources/sap/ui/core/, /resources/sap/ui/layout/, /resources/sap/ui/unified/
verb builder:tasks:buildThemes Available sap.ui.core themes: sap_fiori_3_dark, base, sap_fiori_3_hcb, sap_hcb, sap_fiori_3, sap_fiori_3_hcw
verb builder:tasks:buildThemes Skipping /resources/ui5/community/showcaselib/themes/sap_fiori_3_hcw/library.source.less: Library is not available
verb builder:tasks:buildThemes Skipping /resources/ui5/community/showcaselib/themes/sap_fiori_3_dark/library.source.less: Library is not available
verb builder:tasks:buildThemes Skipping /resources/ui5/community/showcaselib/themes/sap_fiori_3/library.source.less: Library is not available
verb builder:tasks:buildThemes Skipping /resources/ui5/community/showcaselib/themes/base/library.source.less: Library is not available
verb builder:tasks:buildThemes Skipping /resources/ui5/community/showcaselib/themes/sap_fiori_3_hcb/library.source.less: Library is not available
```
