### ISSUE TITLE
Possibility to know when all files has been written by the ui5 builder

### ISSUE THREAD

**Issue by danielang** [SAP/ui5-tooling#588]
## Is your feature request related to a problem? Please describe.
I created a custom build task for building a service-worker that is able to pre cache files.
I use globs and actually the @ui5/fs module to search for those files in the `dist` directory to be able to cache files that are only available after the build is done (e.g. Component-preload.js, library-preload.js, ...).
I noticed and then read in the graceful-fs module that file operations are queued. This results in the issue thatwhen my task starts not all files were written to the filesystem and so my task will miss those files.

## Describe the solution you'd like
It would be nice to have an indication when all file operations of previous tasks are done. Or does something like that already exists and I missed it?
The best way I can currently think of is to have a task stages (build, deploy). Maybe those stages could be configured within the ui5.yml. Stages should only run if their previous stages were completed successfully and all their operations are done.

Those stages can then also used to run e.g. deployment tasks like uploading a zipped version to an SAP system.

## Describe alternatives you've considered
Currently I use a delay (setTimeout) in my task to give graceful-fs the time to do the queued operations. But I hate to do this 😄 ... 

Thank you 🙂

**Comment by RandomByte** [comment]
Hi Daniel, if you have implemented a custom task in the sense of https://sap.github.io/ui5-tooling/pages/extensibility/CustomTasks/, you should be able to access all resources created by previous build steps from the `workspace` DuplexCollection as shown in the [example](https://sap.github.io/ui5-tooling/pages/extensibility/CustomTasks/#example-libtasksgeneratemarkdownfilesjs).

A custom task should not access the file system directly but rather use the provided interfaces to access the virtual file system that is used during the build process.

If this is not possible in your case, could you please share some of your code so we can better understand your approach?

Adding a separate "deploy" stage is an excellent idea which we already keep track of in https://github.com/SAP/ui5-tooling/issues/490

**Comment by danielang** [comment]
Hey Merlin,
thank you for your sugestions. They were very helpful.
During the inspection of other custom tasks in the ui5-ecosystem-repo I noticed that all files of the current project gets prefixed with the namespace - this is why I couldn't find those in my first implementation.

Looking foreward to #490 🙂
