### ISSUE TITLE
ERR_INVALID_PROTOCOL HTTPS not supported

### ISSUE THREAD

**Issue by Fjaoos** [SAP/ui5-tooling#599]
## Expected Behavior
I migrated a freshly created UI5 Fiori Elements Project to Fiori Tools. When I use the command npx fiori run, I want to test the application.

## Current Behavior
The app cannot be tested. It shows the following error:
![image](https://user-images.githubusercontent.com/19299859/153596010-7bb13a38-8dcb-4f1a-a9ed-8352c5daf184.png)

## Steps to Reproduce the Issue
This my configuration:
![image](https://user-images.githubusercontent.com/19299859/153596196-ca7e1cd8-e86f-4faa-8d91-e1113474b197.png)
![image](https://user-images.githubusercontent.com/19299859/153596786-40e6e905-8443-43f9-a993-06ce60a550eb.png)

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): 2.14.4
 * Node.js Version: 16.14.0
 * npm Version: 8.3.1
 * OS/Platform: Windows 10
 * Browser *(if relevant)*: Chrome
 * Other information regarding your environment *(optional)*: Corporate Proxy

## Log Output / Stack Trace
See image above

**Comment by matz3** [comment]
Hi and thanks for reaching out!

Apparently, the fiori-tools-proxy (`@sap/ux-ui5-tooling`) is not part of the UI5 Tooling project (our modules all start with `@ui5/*`). It is rather part of the SAP Fiori tools project, which is not open source as of today.

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-elements/tools-faq

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project.
