### ISSUE TITLE
Startup Parameters Issue

### ISSUE THREAD

**Issue by AdrianDengusiak** [SAP/ui5-tooling#602]
Hi,

I found a problem when testing the app with startup parameters.

## Current Behavior
When I add some test startup parameters to my run script, only a single parameter is present in the URL when localhost launched. The second one is omitted.

```
"scripts": {
   ...
   "start-with-params": "fiori run --open 'test/flpSandbox.html#comtrainingapp-display?param1=true&param2=false'"
}
```

I would like to test my application simulating multiple startup parameters.

## Steps to Reproduce the Issue
1. Add a new start script with two parameters (param1=true, param2=false).
2. Run the application using created script.
3. Only the first parameter is present in the URL: 
http://localhost:8080/test/flpSandbox.html#comtrainingapp-display?param1=true

**param2** is omitted.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.14.3`**
 * Node.js Version: **`17.1.0`**
 * npm Version: `8.1.4`

## Log Output / Stack Trace
```
npm verb cli   'ui5',
npm verb cli   'serve',: timing npm:load Completed in 31ms
npm verb cli   '--open',
npm verb cli   "'test/flpSandbox.html#comtrainingapp-display?param1=true",
npm verb cli   '--port',
npm verb cli   '8080'
```

**Comment by matz3** [comment]
The `&` sign seems to be interpreted by the shell.
Could you please try to use double-quotes like so? (escaping via \ needed within the npm script command)
```
"scripts": {
   ...
   "start-with-params": "fiori run --open \"test/flpSandbox.html#comtrainingapp-display?param1=true&param2=false\""
}
```

**Comment by AdrianDengusiak** [comment]
> The `&` sign seems to be interpreted by the shell. Could you please try to use double-quotes like so? (escaping via \ needed within the npm script command)
> 
> ```
> "scripts": {
>    ...
>    "start-with-params": "fiori run --open \"test/flpSandbox.html#comtrainingapp-display?param1=true&param2=false\""
> }
> ```

Hi @matz3, thanks for your response. I tried this, but then my localhost is not opening in the browser. There's no app preview at all.

**Comment by matz3** [comment]
How does the log output for the `ui5 serve` command look like in that case?

**Comment by AdrianDengusiak** [comment]
It works fine when running this command:

`ui5 serve --open "test/flpSandbox.html#comtrainingapp-display?param1=true&param2=false"  `

The problem is when launching as **'fiori run'** with more than 1 param.

**Comment by vobu** [comment]
hey @tobiasqueck, is there an estimate on when the `fiori` cli will be OSed? would help tremendously to be able to look at the sources for more debugging here

**Comment by matz3** [comment]
@AdrianDengusiak thanks for the feedback. So it doesn't seem to be an issue with the `ui5` CLI.

For issues with the `fiori` command, please use the support channels of the Fiori Tools: https://www.npmjs.com/package/@sap/ux-ui5-tooling#support

**Comment by AdrianDengusiak** [comment]
> @AdrianDengusiak thanks for the feedback. So it doesn't seem to be an issue with the `ui5` CLI.
> 
> For issues with the `fiori` command, please use the support channels of the Fiori Tools: https://www.npmjs.com/package/@sap/ux-ui5-tooling#support

Thanks for your support.

**Comment by zdravko-georgiev** [comment]
Hi @AdrianDengusiak, the solution proposed by @matz3 is the correct one and should actually solve your issue. Indeed there was an issue with the `fiori cli` handling multiple parameters, but this was fix one year ago. If the double quotes are not solving the issue for you, then this might be also npm/Node.js version related.
