### ISSUE TITLE
Remove superfluous `router` dependency in UI5 Server

### ISSUE THREAD

**Issue by LukasHeimann** [SAP/ui5-tooling#606]
## Is your feature request related to a problem? Please describe.
I'm currently debugging for https://github.com/SAP/karma-ui5/issues/410 and found something strange that seems related to my original problem:

UI5 Server has `express` as a dependency, yet the CSP middleware uses the `router` dependency to build a middleware.

## Describe the solution you'd like
The additional `router` dependency could easily be replaced with the `express.Router` middleware. This is a change in two lines of code which seems rather simple: https://github.com/SAP/ui5-server/blob/5f3f5797cbafac3b3c170951b20ee69b9326a48c/lib/middleware/csp.js#L76

## Describe alternatives you've considered
Keep and mix two different router dependencies.

**Comment by matz3** [comment]
Thanks for your suggestion!
The express router relies on express-specific APIs on the `req` / `res` object. This conflicts with the karma-ui5 integration which is based on connect.
So without solving https://github.com/SAP/karma-ui5/issues/410 by enhancing req/res, this change can't be made. And as this is not planned right now, I'm closing this as wontfix.
