### ISSUE TITLE
The packaged UI5 libs are too big

### ISSUE THREAD

**Issue by 974758241** [SAP/ui5-tooling#614]
Packed after the project is too big, can do minimal packaging  ??

**Comment by RandomByte** [comment]
Possible duplicate of https://github.com/SAP/ui5-tooling/issues/361

**Comment by RandomByte** [comment]
Could you please check whether https://github.com/SAP/ui5-tooling/issues/361 covers your question?

If not, kindly explain your problem in more detail.

**Comment by wESADAWQ** [comment]
Okay, I'll keep talking to you when I'm familiar with the source code.

**Comment by 974758241** [comment]
Okay, I'll keep talking to you when I'm familiar with the source code.

**Comment by 974758241** [comment]
Note is the reason for copyright, why not use license. fourth point: I would say it is not necessary to package all i18n files.

**Comment by RandomByte** [comment]
Based on your last comment, I guess you are referring to issue https://github.com/SAP/ui5-tooling/issues/633? Please see my questions in the same.

This issue did not have any details when you opened it back in April. Your new issue has more detail and I think we should continue the discussion there.
