### ISSUE TITLE
Make packing smaller

### ISSUE THREAD

**Issue by 974758241** [SAP/ui5-tooling#633]
# Here are my suggestions and solutions 
## 4. resources are packaged multiple Component-preload.js, such as the sap.m library packaged in this file, so that after the deletion of sap.m in a single file

**Comment by RandomByte** [comment]
Thank you for reaching out. I have a couple of questions to better understand your requirements. I'll outline them for each of your points below: 

Re 1: Are you only referring to comments containing license and copyright information? In that case, as of today, we are unfortunately required to keep those comments in the file for compliance reasons. But I will double check the latest policies on this.  
In case you are referring to other comments, kindly quote an excerpt here. 

Re 2: `*.properties` files should not be part of the `library-preload.js`-bundles provided by the framework. To which files and which bundles do you refer? Also see this related documentation: https://ui5.sap.com/sdk/#/topic/ec753bc539d748f689e3ac814e129563.html

Re 4: It would be great if you could explain this enhancement in more detail. I'm struggling to understand what it refers to. But maybe the self-contained build is close to what you want to achieve? https://sap.github.io/ui5-tooling/pages/CLI/#ui5-build

Thanks!
