### ISSUE TITLE
Failed to resolve library sap.esh.search.ui: Failed to extract package @sapui5/sap.esh.search.ui@1.102.2: No matching version found for @sapui5/sap.esh.search.ui@1.102.2

### ISSUE THREAD

**Issue by LindsayWangGreat** [SAP/ui5-tooling#636]
## Expected Behavior
run ui5 build. it should succeed.

## Current Behavior
the error reported as below.
error Message:
Resolution of framework libraries failed with errors:
Failed to resolve library sap.esh.search.ui: Failed to extract package @sapui5/sap.esh.search.ui@1.102.2: No matching version found for @sapui5/sap.esh.search.ui@1.102.2.

For details, execute the same command again with an additional '--verbose' parameter

## Steps to Reproduce the Issue

1. [check this github](https://github.wdf.sap.corp/grchcpcf/manual-procedure/blob/ui5version_bump_up/app/manual-procedure-design/ui5.yaml)
2. run ui5 build
3. error occurs
specVersion: '2.5'
type: application
framework:
  name: SAPUI5
  version: 1.102.4
  libraries:
  - name: sap.m
  - name: sap.f
  - name: sap.ui.core
  - name: sap.ui.table
  - name: themelib_sap_belize
  - name: sap.ushell
  - name: sap.uxap
  - name: sap.fe.templates
  - name: sap.fe.common
  - name: sap.fe.test
    development: true
  - name: sap.ui.richtexteditor

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): 2.12.1
 * Node.js Version: v12.22.10
 * npm Version: 6.14.16
 * OS/Platform: ios
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
INFO: This project contains an individual @ui5/cli installation which will be used over the global one.
See https://github.com/SAP/ui5-cli#local-vs-global-installation for details.

verb cli:middlewares:base using @ui5/cli version 2.12.1 (from /Users/xxxx/xxxx/xxxx/app/xxx-design/node_modules/@ui5/cli/bin/ui5.js)
verb cli:middlewares:base using node version v12.22.10
info normalizer:translators:ui5Framework Using SAPUI5 version: 1.102.4
info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.esh.search.ui...
⸨░░░░░░░░░░░░░░░░░░⸩ ⠸ : info normalizer:ui5Fra
⚠️  Process Failed With Error

Error Message:
Resolution of framework libraries failed with errors:
Failed to resolve library sap.esh.search.ui: Failed to extract package @sapui5/sap.esh.search.ui@1.102.2: No matching version found for @sapui5/sap.esh.search.ui@1.102.2.
```

**Comment by codeworrior** [comment]
@sapui5/sap.esh.search.ui is indeed missing on npmjs.org, but it was released internally.

AFAICS, it is correct that SAPUI5 1.102.4 refers to sap.esh.search.ui 1.102.2, just the deployment to npmjs.org is missing.

**Comment by RandomByte** [comment]
The missing packages have been published in the relevant versions.

This should be resolved now. Kindly try again and confirm.

**Comment by mhuber9** [comment]
Failed to resolve library sap.fe.navigation: Failed to extract package @sapui5/sap.fe.navigation@1.96.17: No matching version found for @sapui5/sap.fe.navigation@1.96.17.

A other package is missing on npm can you please have a look?

**Comment by matz3** [comment]
> Failed to resolve library sap.fe.navigation: Failed to extract package @sapui5/sap.fe.navigation@1.96.17: No matching version found for @sapui5/sap.fe.navigation@1.96.17.
> 
> 
> 
> A other package is missing on npm can you please have a look?

Can you please state the @ui5/cli version and SAPUI5 version you're using?

**Comment by codeworrior** [comment]
According to https://ui5.sap.com/1.96/patchinfo.html, version 1.96.17 should have been part of SAPUI5 1.96.20 to 1.96.22, but it's indeed missing on npmjs.org. Same for other sap.fe packages, like @sapui5/sap.fe.core.

**Comment by matz3** [comment]
@mhuber9 we're working on it and will provide the missing versions asap.
