### ISSUE TITLE
not able to deploy

### ISSUE THREAD

**Issue by SSOMUNBA** [SAP/ui5-tooling#643]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by flovogt** [comment]
Hi @SSOMUNBA , please provide any further information to get a brief overview what issue you are facing. Feel free to open it again.

**Comment by codeworrior** [comment]
Just in case you missed a deploy functionality: that's not part of the ui5-tooling, but there are custom tasks to achieve this. Check for example https://bestofui5.org/#/packages?search=deploy 

Also see https://github.com/SAP/ui5-tooling/issues/17.
