### ISSUE TITLE
Failed to resolve library sap.fe.templates: Failed to extract package @sapui5/distribution-metadata@1.102.5: No matching version found for @sapui5/distribution-metadata@1.102.5

### ISSUE THREAD

**Issue by risapisa** [SAP/ui5-tooling#644]
## Expected Behavior
run ui5 build. it should succeed.

## Current Behavior
the error reported as below.
Error Message:
Resolution of framework libraries failed with errors:
Failed to resolve library sap.fe.templates: Failed to extract package @sapui5/distribution-metadata@1.102.5: No matching version found for @sapui5/distribution-metadata@1.102.5.

For details, execute the same command again with an additional '--verbose' parameter

## Steps to Reproduce the Issue
<RandomByte: removed internal link, ask me if required>
run ui5 build
error occurs
pecVersion: '2.6'
metadata:
  name: 'processIssues'
  allowSapInternal: true
type: application
framework:
  name: SAPUI5
  version: 1.102.5
  libraries:
    - name: sap.fe.templates
    - name: sap.ui.core
    - name: sap.ui.layout
    - name: sap.m
    - name: sap.ushell
    - name: themelib_sap_fiori_3
    - name: themelib_sap_bluecrystal
    - name: sap.fe.test
    - name: sap.ui.support
    - name: sap.ui.testrecorder

## Context
UI5 Module Version (output of ui5 --version when using the CLI): 2.12.1
Node.js Version: v12.22.10
npm Version: 6.14.16
OS/Platform: ios
Browser (if relevant): unknown
Other information regarding your environment (optional): nothing

## Log Output / Stack Trace
```
13:12:12  info  karmaExecuteTests - [0] info normalizer:translators:ui5Framework Using SAPUI5 version: 1.102.5
13:12:12  info  karmaExecuteTests - [0] info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/distribution-metadata...
13:12:13  info  karmaExecuteTests - [1] [32m02 08 2022 11:12:12.973:INFO [karma-server]: [39mKarma v6.4.0 server started at http://localhost:9876/
13:12:13  info  karmaExecuteTests - [1] [32m02 08 2022 11:12:12.974:INFO [launcher]: [39mLaunching browsers MyHeadlessChrome with concurrency unlimited
13:12:13  info  karmaExecuteTests - [1] [32m02 08 2022 11:12:12.977:INFO [launcher]: [39mStarting browser ChromeHeadless
13:12:13  info  karmaExecuteTests - [1] [32m02 08 2022 11:12:13.509:INFO [Chrome Headless 90.0.4430.212 (Linux x86_64)]: [39mConnected on socket UTS1FeIVXHlEWjvFAAAB with id 30074098
13:12:13  info  karmaExecuteTests - [0] 
13:12:13  info  karmaExecuteTests - [0] ⚠️  Process Failed With Error
13:12:13  info  karmaExecuteTests - [0] 
13:12:13  info  karmaExecuteTests - [0] Error Message:
13:12:13  info  karmaExecuteTests - [0] Resolution of framework libraries failed with errors:
13:12:13  info  karmaExecuteTests - [0] Failed to resolve library sap.fe.templates: Failed to extract package @sapui5/distribution-metadata@1.102.5: No matching version found for @sapui5/distribution-metadata@1.102.5.
```

**Comment by RandomByte** [comment]
Thanks for reporting.

npm publishing of SAPUI5 1.102.5 is unfortunately delayed at the moment. We are working on publishing it ASAP.

**Comment by RandomByte** [comment]
SAPUI5 1.102.5 has been published to the npm registry. Please try using it again.
