### ISSUE TITLE
Teste

### ISSUE THREAD

**Issue by EdsonPrazeres** [SAP/ui5-tooling#648]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by flovogt** [comment]
Hi @EdsonPrazeres, looks like a test issue. So closing it.
