### ISSUE TITLE
Page Editor crashes when changing custom column order

### ISSUE THREAD

**Issue by jvanattedev** [SAP/ui5-tooling#689]
## Expected Behavior
The page editor contains arrow keys (up and down) to change the order of columns in a table for a Fiori Elements application. When clicking the arrows, the respective column should change.

## Current Behavior
When clicking one of the arrows, the page editor crashes.

## Steps to Reproduce the Issue
The Fiori Elements application contains a number of "regular" columns created by annotations. It contains 1 column created via an extension (created using the Guided Development).
1. Open the Page Editor
2. Click the arrow of the custom column of which you want to change the order.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.14.14`**
 * Node.js Version: **`16.17.1`**
 * npm Version: `8.9.2`
 * OS/Platform: `Windows 10`
 * Browser *(if relevant)*: `not applicable - crash occurs in the tooling`

## Log Output / Stack Trace
not applicable - crash occurs in the tooling

**Comment by flovogt** [comment]
Hi @jvanattedev,
this is the repository of the UI5 Tooling which does not provide any page editor. 
Please, open a ticket in SAP ticket system for managing incidents.

**Comment by boghyon** [comment]
Hi @jvanattedev , in the [OpenUI5 slack thread](https://openui5.slack.com/archives/C0A7MHSSJ/p1666959758491319), I meant the repo https://github.com/SAP/open-ux-tools, not ui5-tooling.
