### ISSUE TITLE
Deno.js Support

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#698]
## Is your feature request related to a problem? Please describe.
Deno.js is gaining its maturity, and with introducing of the NPM-compatibility, it might be a real alternative to Node.js.

## Describe the solution you'd like
I would like that UI5 Tooling could run on Deno.js environment out-of-box.
Currently, UI5 Tooling tells nothing about the Deno.js support.

**Comment by RandomByte** [comment]
Thank you for your input! At this time, we do not plan to officially support JavaScript runtimes other than Node.js.

Have you already tried using UI5 Tooling in Deno? It would be helpful for us to have a rough overview of the issues that would need to be resolved.

It might make sense to use the [UI5 Tooling v3 beta-release](https://sap.github.io/ui5-tooling/updates/migrate-v3/) for such testing. At least the [documentation](https://deno.land/manual@v1.28.1/node/npm_specifiers) and the [related issue](https://github.com/denoland/deno/issues/15960) seem to suggest better chances for ESM packages. Which is the case for UI5 Tooling v3.

If we get UI5 Tooling running in Deno, we would also need to enhance our CI/CD processes to test this runtime and potentially invest additional time in fixing Deno-specific issues that we might face in the future. For this investment, I think we must first clarify the motivation and benefits for UI5 developers to use Deno over Node.js.
