### ISSUE TITLE
Fiori apps isnt running after upgate of  "@sap/ux-ui5-tooling": "^1.8.6"

### ISSUE THREAD

**Issue by krantik26** [SAP/ui5-tooling#755]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by RandomByte** [comment]
Hi and thanks for reaching out!

Apparently, the `@sap/ux-ui5-tooling` package is not part of the UI5 Tooling project (our packages all start with `@ui5/*`). It is rather part of the SAP Fiori tools project.

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

You can also find related documentation and support channels here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project.
