### ISSUE TITLE
VersionInfoGenerator doesn't consider dependencies from `includeDependency`

### ISSUE THREAD

**Issue by petermuessig** [SAP/ui5-tooling#766]
## Expected Behavior
When an `application` defines the `includeDependency` in the `ui5.yaml` it should find the dependencies of the included dependency and not report an error.

## Current Behavior
When a custom `library` is included via `includeDependency` into an `application` the `versionInfoGenerator` processor reports the following error:

```sh
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.ui.core' defined in the manifest.json or .library file of project 'ui5.ecosystem.demo.tslib'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
```

## Steps to Reproduce the Issue

I will asap upload a change to the `ui5-ecosystem-showcase` which can be used to reproduce this issue: 

- `git clone https://github.com/ui5-community/ui5-ecosystem-showcase.git`
- `pnpm install`
- `pnpm build:ts`

This works as soon as you can find the package `ui5-lib-ts` in the repository.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **16.19.0**
 * npm Version: `8.19.3`
 * OS/Platform: `Mac`
 * Browser *(if relevant)*: `n/a`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

Issue in VSCode debugger:

![image](https://user-images.githubusercontent.com/1589419/217539894-81f942af-b419-4b65-bd3c-3914704bc73c.png)

```sh
info builder:processors:versionInfoGenerator Cannot find dependency 'sap.ui.core' defined in the manifest.json or .library file of project 'ui5.ecosystem.demo.tslib'. This might prevent some UI5 runtime performance optimizations from taking effect. Please double check your project's dependency configuration.
```

**Comment by RandomByte** [comment]
Hi Peter, thanks for reporting. Just let us know once `ui5-lib-ts` is available. We'll wait with the analysis until then 👍

**Comment by petermuessig** [comment]
Oh, missed to comment here. The ui5-lib-ts is available...

**Comment by matz3** [comment]
@petermuessig the project is using `@ui5/cli` v2.x which is deprecated.
Could you please upgrade to v3 and try again?

**Comment by flovogt** [comment]
@petermuessig did you have another try with v3?

**Comment by petermuessig** [comment]
Sorry for the late reply, but I think this issue is not relevant anymore. At least, I can't reproduce it anymore. But I found another issue for which I need to open a ticket. Tooling extension dependencies from e.g. libraries couldn't be found when using includeDependency and building the library in the app!
