### ISSUE TITLE
ui5-cli: Broken changelog link for v3 migration

### ISSUE THREAD

**Issue by xLexip** [SAP/ui5-tooling#770]
Hey there,
the link for the v3 migration guide of the ui5-cli repo leads to a 404. The link also appears in console errors, e.g.:
`Standard task generateManifestBundle, referenced by custom task webide-extension-task-updateManifestJson in project *********, has been removed in this version of UI5 Tooling and can't be referenced anymore. Please see the migration guide at https://sap.github.io/ui5-tooling/updates/migrate-v3/`

**Broken Link:** [sap.github.io/ui5-tooling/updates/migrate-v3/](https:sap.github.io/ui5-tooling/updates/migrate-v3/)
**Change:** https://github.com/SAP/ui5-cli/blame/a984a1873a1a54803efd8c0da8e01520355ede13/CHANGELOG.md#L104

BR
Lexip

CC: @RandomByte

**Comment by codeworrior** [comment]
Sorry for the inconvenience. This is temporary issue and should be fixed soon, once we make the v3 documentation the default documentation.

It's basically a chicken/egg problem. We wanted to release the tooling with a link pointing to the future documentation, but wanted to release the documentation only after the tooling is available.

Once the v3 documentation has been enabled, we'll check this again to be sure.

**Comment by flovogt** [comment]
Hi @xLexip, thanks a lot for reporting this issue. Documentation is re re-deployed. Now, the link should work.
