### ISSUE TITLE
ui5 serve wrongly takes care on builder/resources/excludes after migration to 3.0.0 

### ISSUE THREAD

**Issue by hschaefer123** [SAP/ui5-tooling#779]
Hi,
congrats to the new new major 3.0.0!

After migrating a customer project using the latest version, i was struggling why my indexLocal.html is no more served.

The reason is my ```ui5.yaml``` config entry

```
builder:
  resources:
    excludes:
      - "indexLocal.html"
```
which is used to exclude files from bundling for deployment.

It seems, that serve also take care on this, because after renaming it, everthing works fine,
but file will be part of dist.

## Expected Behavior
This config section just controls the resources for building the dist folder.

## Current Behavior
Also serve skips started to skip defined files. 

## Steps to Reproduce the Issue
- Having a custom file inside webapp folder
- Exclude this file inside ui5.yaml the way shown above (builder/resources/excludes/- "indexLocal.html"
- launch ui5 server (in my case from above mono repo level pointing out to the config path)
- ui5 serve --config ui/shop/ui5.yaml
- indexLocal.html will not be part of directory index ans is also not callable
- change exclude name and restart service
- now file will be served

## Context
 * Node.js Version:  18.14.0**`unknown`**
 * npm Version: 9.3.1
 * OS/Platform: macOS Ventura 13.2

Regards
Holger

**Comment by RandomByte** [comment]
Thanks for reporting Holger! This is indeed a bug and we are already working on a fix.
