### ISSUE TITLE
Build Execution Time in UI Tooling 3.0

### ISSUE THREAD

**Issue by shaiSAP** [SAP/ui5-tooling#781]
After upgrading to UI Tooling 3.0 a build which took a few seconds now takes about 100 seconds.
(It might be a result of an invalid/incomplete configuration).
I'm attaching the verbose log of the build.
[build_log.txt](https://github.com/SAP/ui5-tooling/files/10742029/build_log.txt)

**Comment by shaiSAP** [comment]
Thanks for the quick response and the detailed info.
If this is the case with any custom task, there should be a warning regarding it.
Moreover, I wonder wouldn't it be easier to change the default behaviour: Build all the project dependencies only if a custom task explicitly requires access to them.

**Comment by RandomByte** [comment]
Thanks for creating the issue!

> Moreover, I wonder wouldn't it be easier to change the default behaviour: Build all the project dependencies only if a custom task explicitly requires access to them.

Yes, you are right. Sadly there is no way to tell for UI5 Tooling whether an existing custom task requires access to dependencies. This is only possible with the newly introduced [`determineRequiredDependencies` callback](https://sap.github.io/ui5-tooling/stable/pages/extensibility/CustomTasks/#required-dependencies).

Therefore, we have to assume that all existing custom tasks _might_ require access to dependencies.

**Comment by RandomByte** [comment]
The `ui5-task-nwabap-deployer` custom task has been updated as per https://github.com/pfefferf/ui5-nwabap-deployer/issues/60

Updating the dependency should resolve the performance issue you are facing.
