### ISSUE TITLE
I have problem while creating project in SAP UI5. It showing me error like....unable to find the 'ui5template/basicSAPUI5ApplicationProject/BasicSAPUI5AppplicationProjectTemplateWithManifest.zip'resource in the 'sap.watt.saptoolsets.fiori.project.ui5template' plugin

### ISSUE THREAD

**Issue by PriyadharshiniArul** [SAP/ui5-tooling#791]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by flovogt** [comment]
Hi @PriyadharshiniArul, thanks for opening this issue. 
This is the repository for UI5 Tooling related modules and issues. The  plugin `sap.watt.saptoolsets.fiori.project.ui5template` you have mentioned is not part of this, so please open an SAP support incident and provide more details there.
