### ISSUE TITLE
UI5 Workspaces RFC link in the documentation does not work

### ISSUE THREAD

**Issue by jacek-wozniczak-ns** [SAP/ui5-tooling#794]
Hi,

the link to https://github.com/SAP/ui5-tooling/blob/rfc-local-dependency-resolution/rfcs/0006-local-dependency-resolution.md

gives 404.

BR,
Jacek

**Comment by matz3** [comment]
Thanks for reporting this!
Here is the correct link: https://github.com/SAP/ui5-tooling/blob/main/rfcs/0006-local-dependency-resolution.md
I'll update the documentation soon.
