### ISSUE TITLE
Exit code 0 although deployment failed

### ISSUE THREAD

**Issue by matt1as** [SAP/ui5-tooling#801]
## Expected Behavior
On failed deployed exit code is expected to be non zero. This if vital for building a functional CI/CD pipeline. Today we cannot see if the deploy has failed or succeded.

## Current Behavior
Exit code is zero although deploy failed

## Steps to Reproduce the Issue
Deploy application to a request that has already been released. Run `echo $? ` to see the exit code.

```
npx fiori deploy --config ui5-deploy.yaml

Confirmation is required to deploy the app:

    Application Name: xxxxxxxxx
    Package: xxxxxxx
    Transport Request: DNGK906800
    Destination: gateway
    SCP: false
    
    
✔ Start deployment (Y/n)?
… yes
info builder:custom deploy-to-abap Create Archive
info builder:custom deploy-to-abap test/unit/controller/View1-dbg.controller.js added
info builder:custom deploy-to-abap test/unit/controller/Detail.controller.js added
info builder:custom deploy-to-abap test/integration/pages/View1.js added
......
......
.....
info builder:custom deploy-to-abap 
ERR! builder:custom deploy-to-abap Request DNGK906800 is already released
ERR! builder:custom deploy-to-abap Text file resources/sap-ui-version.json has not been uploaded
ERR! builder:custom deploy-to-abap Request DNGK906800 is already released
ERR! builder:custom deploy-to-abap Text file sap-ui-cachebuster-info.json has not been uploaded
info builder:custom deploy-to-abap 
info builder:custom deploy-to-abap * Updating the Application Index *
.....
ERR! builder:custom deploy-to-abap SAP_Transaction: For backend administrators: use ADT feed reader "SAP Gateway Error Log" or run transaction /IWFND/ERROR_LOG on SAP Gateway hub system and search for entries with the timestamp above for more details
ERR! builder:custom deploy-to-abap SAP_Note: See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)
~/projects/project_name (master)$ echo $?
0
```

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`2.14.16 `**
 * Node.js Version: **`v16.19.0`**
 * npm Version: `8.19.3`
 * OS/Platform: `Business Application Studio and BitBucket Pipelines`
 * Other information regarding your environment *(optional)*: `This occurs both when running on BAS and in a CI/CD pipeline on bitbucket`

**Comment by flovogt** [comment]
Hi @matt1as, thanks a lot for opening this issue. Unfortunately, the task which does the actual deployment named `deploy-to-abap` is not part of UI5 Tooling. It is offered by package [@sap/ux-ui5-tooling](https://www.npmjs.com/package/@sap/ux-ui5-tooling) also known as SAP Fiori Tools project which is not part of the UI5 Tooling project (our modules all start with @ui5/*).

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US
