### ISSUE TITLE
How to integrate External Librairies in SAPUI5/UI5/Fiori

### ISSUE THREAD

**Issue by christophelannoyadeo** [SAP/ui5-tooling#802]
Hi everyone,
I want to use and external library @datadog/browser-rum

It works perfectly if I follow tte tips n this blog https://blogs.sap.com/2017/04/30/how-to-include-third-party-libraries-modules-in-sapui5/. From this lastest, we on upload the js file in the project.

But I don't really want to do that.

I tried to follow this blog also https://blogs.sap.com/2021/11/15/using-npm-packages-in-ui5-without-shims/ so without using shims (I tried also with shims but I nether succed).
So I would like to use npm packages as proposed in the blog.

So to test it I am working with BAS based on a demo project Walkthrough demo.

I have set the dependancy in package.json
![2023-03-15_18h20_45](https://user-images.githubusercontent.com/78436845/225610121-8e078a41-100f-4d05-8cb0-930ed898377d.png)

Then I use in define in my controller
![image](https://user-images.githubusercontent.com/78436845/225610453-760edbc4-1a86-4704-aef3-7018c3e651a2.png)

But when i want to test, it fails. The file is not found despite it exist in te dist folder
![image](https://user-images.githubusercontent.com/78436845/225610727-8eb77092-5bec-46bf-8e7e-4a90fb3bb1be.png)

You can see that this file exists in the folder after building it
![image](https://user-images.githubusercontent.com/78436845/225610861-628f8349-63c8-42fe-a730-01361f454173.png)

I think i have not set something wrong but I don't know where (in ui5.yaml ??)

May I ask you a clue or tips or example that could help ?

Thanks in advance
Kind Regards
Christophe Lannoy

**Comment by christophelannoyadeo** [comment]
Hi @flovogt ,
thanks a lot for your help and linked.

- for shims, I have found that I have an issue. In BAS, i can only use spec 2.6 and I need to be in 3.0 to be able to use "@" in the name definition. If I want to use shims, in ui5.yaml, in " configurations" section the name as to be the same as package.json.  But in dependancy, I am obliged to use @datadog/browser-rum so I think just right now 
- so I have tried to use your example but I still ecnounter a probleme when strating my application
In controler I have put this code 
`sap.ui.define([
	"sap/ui/core/UIComponent",
	"sap/ui/model/json/JSONModel",
	"sap/ui/Device",
	"sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4"
], function (UIComponent, JSONModel, Device, _DD_RUM) {
	
	
  "use strict";

// Provides a shim for the datadog-rum library
sap.ui.loader.config({
    paths: {
      "sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4": "https://www.datadoghq-browser-agent.com/datadog-rum-v4.js"
    },
    shim: {
      "sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4": {
        amd: true,
        exports: "_DD_RUM"
      }
    }
  });

	return UIComponent.extend("sap.ui.demo.walkthrough.Component", {

		metadata: {
			interfaces: ["sap.ui.core.IAsyncContentCreation"],
			manifest: "json"
		},

		init: function () {
			// call the init function of the parent
			UIComponent.prototype.init.apply(this, arguments);
			
			// set data model
			var oData = {
				recipient: {
					name: "World"
				}
			};
			var oModel = new JSONModel(oData);
			this.setModel(oModel);

			// set device model
			var oDeviceModel = new JSONModel(Device);
			oDeviceModel.setDefaultBindingMode("OneWay");
			this.setModel(oDeviceModel, "device");

			// create the views based on the url/hash	
			this.getRouter().initialize();
			

			 
		},

		getContentDensityClass : function () {
			if (!this._sContentDensityClass) {
				if (!Device.support.touch) {
					this._sContentDensityClass = "sapUiSizeCompact";
				} else {
					this._sContentDensityClass = "sapUiSizeCozy";
				}
			}
			return this._sContentDensityClass;
		}

	});

});`
I launch npm run build and launch the application, but it generates a probleme when loading 
`'sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4.js': failed to load 'sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4.js' from ../thirdparty/datadog-rum-v4.js: script load error`

![2023-03-20_09h55_26](https://user-images.githubusercontent.com/78436845/226291444-2df1c23e-daa9-43bb-8826-15b876f4fd20.png)

As It works for you application, I don't understand why I am stuck on mine..

Any clue?

best Regards

**Comment by flovogt** [comment]
Hi @christophelannoyadeo,
would be awesome if you could share the app via a github repository or as an zip file in the issue here.
Its quite hard to judge on the reason here.

**Comment by christophelannoyadeo** [comment]
Hi @flovogt 
thanks for this help

Here are the repo
https://github.com/christophelannoyadeo/datadog_rumsapui5.git

**Comment by flovogt** [comment]
Sorry @christophelannoyadeo for not responding so long. Is the issue still active?

**Comment by christophelannoyadeo** [comment]
Yes this issue is still active

**Comment by flovogt** [comment]
We had another look at your application:

1. Move the loader config code to the top of the file
2. Remove the `.js` part in the loader config path property
3. Change the `exports` property to `DD_RUM`


```js
// Provides a shim for the datadog-rum library
sap.ui.loader.config({
    paths: {
      "sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4": "https://www.datadoghq-browser-agent.com/datadog-rum-v4"
    },
    shim: {
      "sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4": {
        amd: true,
        exports: "DD_RUM"
      }
    }
  });
 
sap.ui.define([
	"sap/ui/core/UIComponent",
	"sap/ui/model/json/JSONModel",
	"sap/ui/Device",
	"sap/ui/demo/walkthrough/thirdparty/datadog-rum-v4"
], function (UIComponent, JSONModel, Device, _DD_RUM) {

.....

			this.getRouter().initialize();
			_DD_RUM && _DD_RUM.init({....
              });

```
