### ISSUE TITLE
Cannot run the app 

### ISSUE THREAD

**Issue by MuhammadAli94** [SAP/ui5-tooling#805]
## Expected Behavior
{need to be able to run the app using the command UI5 serve -o}

## Current Behavior
{Failed to create a UI5 project from module grunt-build at C:\Users\user\VSC_code_Workspace\ehs.pma.prod.crr.mons1. Make sure the path is correct and a project configuration is present or supplied.}

## Steps to Reproduce the Issue

1Stack Trace:
Error: Failed to create a UI5 project from module grunt-build at C:\Users\user\VSC_code_Workspace\ehs.pma.prod.crr.mons1. Make sure the path is correct and a project configuration is present or supplied.    
    at projectGraphBuilder (file:///C:/Users/user/AppData/Roaming/npm/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/projectGraphBuilder.js:120:9)
    at async graphFromPackageDependencies (file:///C:/Users/user/AppData/Roaming/npm/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/graph.js:70:23)
    at async serve.handler (file:///C:/Users/user/AppData/Roaming/npm/node_modules/@ui5/cli/lib/cli/commands/serve.js:89:11)

If you think this is an issue of the UI5 Tooling, you might report it using the following URL: https://github.com/SAP/ui5-tooling/issues/new/choose

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by d3xter666** [comment]
Hi @MuhammadAli94,

This error seems like an indicator that the `ui5 serve -o` command is executed in a project/place that does not contain a ui5.yaml file.
If there's a `ui5.yaml file`, I could guess that the `grunt-build` task is run in the wrong context (it's run not from the project's root folder where ui5.yaml is located)

Could you provide more details about the project?
Is the `grunt-build` script a packege.json?

Providing the `ui5.yaml` and the `grunt-build` task/script would give us a bit more context, so we do not play a guessing game.

Best regards
