### ISSUE TITLE
Shims no longer bundled after migration to v3

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-tooling#807]
Hi, I am creating this issue because the 'get a slack invite' website seems to crash on email submission..
So - I've followed the migration guide and attempted to build an app with a dedicated library using the `-a` flag. Earlier this used to mount all shims under the `/resources` dist directory, but now only some? shims are mounted. I cannot seem to find any info regarding shims & this behavior in the new tooling version. What am I missing?

## Expected Behavior
Shims in libraries should be in the `dist` of the consuming app

## Current Behavior
None or only some shims are bundled in the `dist`

## Steps to Reproduce the Issue
{...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`3.0.5`**
 * Node.js Version: **`16.9.1`**
 * npm Version: `8.19.3`
 * OS/Platform: `Win11`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

**Comment by dfenerski** [comment]
Follow-up: `ui5 tree` lists the shims that **do** get bundled. So if it is in the dep graph, it gets properly bundled. The question then remains why are some missing from the dep graph when they weren't missing with v2.14 ?

**Comment by dfenerski** [comment]
Another follow-up: disabling `devDependency` analysis [here](https://github.com/SAP/ui5-project/blob/ef3e56996111233aaa04410c95f11b1c3495a9b2/lib/graph/providers/NodePackageDependencies.js#L128) and [here](https://github.com/SAP/ui5-project/blob/ef3e56996111233aaa04410c95f11b1c3495a9b2/lib/graph/providers/NodePackageDependencies.js#L136) solved my problem. I think this confirms the issue as I understand it in the comment above - the tooling refuses to bundle when a shim is duplicated twice in a consumer app and in an underlying lib. However I think the use case is legit - the lib shims & marks as `dependency` once; any consumer app specifies the lib as dep and the shims as `devDependency` for type usage only.

Am I wrong? Can this behavior be tweaked?

Additional question, perhaps a sillier one - why are `depDependencies` even bundled & shipped to the browser? Isn't their point to be `dev` only ?

Any information on those questions is appreciated. Thanks in advance.

**Comment by d3xter666** [comment]
Hi @dfenerski ,

Would be able to elaborate a little bit more?

What I understand so far is that you have couple projects an `app` and some `library` that is dependency of that `app`.
The `rxjs` is a dependency of the `library`, but in the `app` is used only when developing (`devDependencies`), so you'd have TS definitions available for it. And you'd end up with a structure like this:

#### App structure
```sh
app/
  \_ node_modules/
    \_ library/
      \_ node_modules/
        \_ rxjs/
```

#### app's package.json
```json
{
  "name": "app",
  ...
  "dependencies": {
    "lib": "^X.Y.Z"
  },
  "devDependencies": {
    "rxjs": "^X.Y.Z"
  }
}
```

#### library's package.json
```json
{
  "name": "lib",
  ...  
  "dependencies": {
    "rxjs": "^X.Y.Z"
  }
}
```

#### library's shim for rxjs (eventually) in ui5.yaml
```yaml
specVersion: "3.0"
kind: extension
type: project-shim
metadata:
  name: rxjs
shims:
  configurations:
    rxjs:
      specVersion: "3.0"
      type: module
      metadata:
        name: rxjs
      resources:
        configuration:
          paths:
            /resources/: ""
```

If I understand correctly your complaint, you'd expect that dependencies for the `library` would be in the `dist/` folder of the `app` when buliding the `app`.

Did I understand it correctly?
