### ISSUE TITLE
Documentation not updated for v3

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-tooling#808]
## Expected Behavior
Documentation should specify which tasks apply for which tooling version, or specify tasks only from the latest tooling version.

## Current Behavior
`uglify` and `createDebugFiles` are mentioned as the 'go-to' tasks but those tasks are no longer available in v3.

## Steps to Reproduce the Issue
https://sap.github.io/ui5-tooling/v3/pages/Configuration/#minification

**Comment by flovogt** [comment]
Good catch! Thanks a lot. We will provide a fix for that one.

**Comment by d3xter666** [comment]
Reopening this one as the property in the configuration is missing in the schema. 
We'd adjust the documentation, but would also see if such properties are beneficial for the end users. Leaving this open for now

**Comment by matz3** [comment]
> Reopening this one as the property in the configuration is missing in the [schema](https://sap.github.io/ui5-tooling/schema/ui5.yaml.json).
We'd adjust the documentation, but would also see if such properties are beneficial for the end users. Leaving this open for now

To clarify this: It's not only missing in the schema, but the whole feature of having this option via the configuration is currently not implemented.

**Comment by flovogt** [comment]
I'll close this issue. The documentation is updated for V3 tasks.

The other mentioned missing feature might come in future, but it is not related to the original issue.
