### ISSUE TITLE
Shims not bundled if installed under npm alias for v3

### ISSUE THREAD

**Issue by dfenerski** [SAP/ui5-tooling#809]
## Expected Behavior
Automatic dependency analysis should be able to pick up exposed name of npm dependency, regardless of the underlying package.

## Current Behavior
If one runs `npm i kool@npm:case` and then provides shim configuration for `kool`, the tooling won't pick it up. 

## Steps to Reproduce the Issue
1. open npm sample app
2. install a npm package under alias, [reference](https://stackoverflow.com/questions/56134857/how-to-install-npm-package-under-alias-or-different-name)
3. provide a basic shimming config like this one 
![image](https://user-images.githubusercontent.com/48520530/227464408-4fd82a5a-6c09-403f-a5dc-752ad8844cba.png)

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`3.0.5`**
 * Node.js Version: **`16.19.1`**
 * npm Version: `8.19.3`
 * OS/Platform: `Win11`
 * Browser *(if relevant)*: `not relevant`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace
I can provide additional log traces / info if needed.

**Comment by d3xter666** [comment]
Thanks for reaching out, @dfenerski 

Indeed npm aliases are not bundled when building.

**Comment by d3xter666** [comment]
HI @dfenerski,

The issue has been resolved in @ui5/project v3.3.0 and is available through the @ui5/cli version 3.1.2

Cheers
