### ISSUE TITLE
Confusing availability of SAPUI5 SDK Version

### ISSUE THREAD

**Issue by marianfoo** [SAP/ui5-tooling#816]
## Expected Behavior
Using Versions defined in `manifest.json`

## Current Behavior
Message: `Version 1.108.11 is not available on the SAPUI5 SDK, using version 1.111.2 instead.`

## Steps to Reproduce the Issue

```sh
git clone https://github.com/marianfoo/ui5-cc-excelUpload
pnpm i
npm run start:v2fe:108
```

Message:
Message: `Version 1.108.11 is not available on the SAPUI5 SDK, using version 1.111.2 instead.`
![image](https://user-images.githubusercontent.com/13335743/229726115-0d790dad-3342-46cd-8e03-7fe1f68c2f73.png)

If i change the version in the [manifest](https://github.com/marianfoo/ui5-cc-excelUpload/blob/5bcd49879a450248dbea8b48714830dbda89aa64/examples/packages/ordersv2fe/webapp/manifest.json#L56) to `1.108.9` following message appear:

Message: `Version 1.108.9 is not available on the SAPUI5 SDK, using version 1.108.11 instead.`
![image](https://user-images.githubusercontent.com/13335743/229726460-311cbc2a-a5ec-41e0-8624-b93887213a8d.png)

With version `1.108.10` no message appears
![image](https://user-images.githubusercontent.com/13335743/229726606-73e8782b-5313-42d2-a546-c0e8e9b3e9f1.png)

The versions are available on the CDN, under this URL, right?:
https://ui5.sap.com/1.108.11/resources/sap-ui-core.js
https://ui5.sap.com/1.108.10/resources/sap-ui-core.js
https://ui5.sap.com/1.108.9/resources/sap-ui-core.js

Hier sind die Versionen auch aufgeführt:
https://sapui5.hana.ondemand.com/versionoverview.html

I am just confused how to select the available UI5 version.

**Comment by matz3** [comment]
`fiori-tools-proxy` is part of the `@sap/ux-ui5-tooling` module. The SAP Fiori Tools project is not part of the UI5 Tooling project (our modules all start with `@ui5/*`).

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

**Comment by marianfoo** [comment]
Thanks @matz3 , you´re right.
Might remove this component if this does not work.
Nevertheless, i try at the SAP Community
https://answers.sap.com/questions/13863303/confusing-availability-of-sapui5-sdk-version.html
