### ISSUE TITLE
Certain Shims not working since ui5-tooling-modules version 0.7.12

### ISSUE THREAD

**Issue by Talwynox** [SAP/ui5-tooling#819]
## Expected Behavior
The build should complete successfully with version 0.7.12, with no errors related to the handling of shim projects.

## Current Behavior
When upgrading from version 0.7.11 to version 0.7.12, the build process fails due to the incorrect handling of some shim projects. This issue seems to have been caused by a change in the Rollup version from 3.17.2 to 3.20.0.

## Steps to Reproduce the Issue
1. Create UI5 App with ui5-tooling-modules: ^0.7.12
2. Add @stomp/stompjs (might also happen with other packages) as shim
3. Add a component which imports stompjs
4. run ui5 build

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): `3.0.3`
 * Node.js Version: `v18.12.1`
 * npm Version: `9.6.1`
 * OS/Platform: `win10`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace
`error lbt:bundle:Resolver **** error: missing module @stomp/stompjs.js, required by .../messageQueue/ConnectionStomp.js`

**Comment by RandomByte** [comment]
The ui5-tooling-modules extension is not part of this repository.

Please file an issue at https://github.com/ui5-community/ui5-ecosystem-showcase/issues instead
