### ISSUE TITLE
Fiori element report unable to load - Error while processing building block FilterBar

### ISSUE THREAD

**Issue by bryan-wee** [SAP/ui5-tooling#821]
## Expected Behavior
List report to load.

## Current Behavior
Since friday (21/3/2023), all subaccounts cant load the same report with the error below. No deployment was done on Friday from our development.

Error on page: 
Error while processing building block FilterBar
Trailing text was found in the XML:
How the building block was called
<macroFilterBar:FilterBarAPI xmlns:template="http://schemas.sap.com/sapui5/extension/sap.ui.core.template/1" xmlns:core="sap.ui.core" xmlns:mdc="sap.ui.mdc" xmlns:control="sap.fe.core.controls" xmlns:macroFilterBar="sap.fe.macros.filterBar" xmlns:macro="sap.fe.macros" xmlns:internalMacro="sap.fe.macros.internal" xmlns:customData="http://schemas.sap.com/sapui5/extension/sap.ui.core.CustomData/1" id="{this>undefinedValue}" search="{this>undefinedValue}" filterChanged="{this>undefinedValue}" afterClear=".onAfterClear" internalSearch=".handlers.onSearch" internalFilterChanged=".handlers.onFiltersChanged" stateChange=".handlers.onStateChange">
		<control:FilterBar core:require="{API: 'sap/fe/macros/filterBar/FilterBarAPI'}" id="{this>undefinedValue}" liveMode="false" delegate="{name:'sap/fe/macros/filterBar/FilterBarDelegate', payload: {entityTypePath: 'undefined'}}" variantBackreference="fe::PageVariantManagement" showAdaptFiltersButton="true" showClearButton="false" p13nMode="Item,Value" search="API.handleSearch($event)" filtersChanged="API.handleFilterChanged($event)" filterConditions="{this>undefinedValue}" suspendSelection="false" showMessages="false" toggleControl="{this>undefinedValue}" initialLayout="compact" propertyInfo="{this>undefinedValue}" customData:localId="{this>undefinedValue}" visible="{this>undefinedValue}" customData:hideBasicSearch="{this>undefinedValue}" customData:showDraftEditState="false" customData:useSemanticDateRange="true" customData:entityType="{this>undefinedValue}" customData:parameters="{this>undefinedValue}">
			<control:dependents>
				{this>undefinedValue}
			</control:dependents>
			<control:basicSearchField>
			<mdc:FilterField id="BasicSearchField" placeholder="{sap.fe.i18n>M_FILTERBAR_SEARCH}" conditions="{$filters>/conditions/$search}" dataType="sap.ui.model.odata.type.String" maxConditions="1"/>
		</control:basicSearchField>
			<control:filterItems>
				{this>undefinedValue}
			</control:filterItems>
		</control:FilterBar>
	</macroFilterBar:FilterBarAPI>

Error in the console: 
Log-dbg.js:493 2023-04-23 22:17:18.912500 An error occurs while computing the title hierarchy and calling focus method - TypeError: Cannot read properties of undefined (reading 'getHeaderExpanded')  
 TypeError: Cannot read properties of undefined (reading 'getHeaderExpanded')
    at o.t [as _setInitialFocus] (ListReportController-dbg.controller.js:446:40)
    at o.e [as onPageReady] (ListReportController-dbg.controller.js:336:14)
    at r.e [as onPageReady] (TemplateComponent-dbg.js:107:24)
    at RootViewBaseController-dbg.js:139:31

## Steps to Reproduce the Issue
Just a simple fiori element list from a CAP service with additional custom search parameters in the filter bar. Metadata loading on network in the browser debugging tool looks ok. App is opened from launchpad of the sap build workzone, standard edition.

## Version 
From the browser debugging console, the sapui5 resources version is 1.113.0

**Comment by RandomByte** [comment]
Based on the error and general problem description, this does not seem to be a UI5 Tooling issue.

Please raise an SAP Support incident over at https://support.sap.com/en/index.html
