### ISSUE TITLE
Vite.js vs. UI5 Tooling

### ISSUE THREAD

**Issue by pubmikeb** [SAP/ui5-tooling#827]
I've read the [Getting started with UI5 Web Components in 2021](https://blogs.sap.com/2021/05/28/getting-started-with-ui5-web-components-in-2021) post, where Vite.js is mentioned, but there is no any reference to UI5 Tooling.

How does [Vite.js](https://vitejs.dev) relate to [UI5 Tooling](https://sap.github.io/ui5-tooling)?

It looks like both tools are focused on the same issue: tooling & building the app before deployment to production.
Please, correct me, if I'm wrong.

Therefore, my questions:

1. Can one replace another?
2. When one should be prefered over another one?
3. Can be Vite.js used with the OpenUI5 projects?

**Comment by RandomByte** [comment]
UI5 Tooling is only catering to development with the OpenUI5 and SAPUI5 frameworks.

UI5 Web Components is an independent offering, for which UI5 Tooling is neither required nor particularly useful. Hence, Petar uses a more useful tool, Vite.js, for the scenario in his blog post.

Of course there are scenarios where UI5 Web Components are used in an OpenUI5 based application for example. In this case it can make sense to use UI5 Tooling to handle the OpenUI5 framework part of the project.
