### ISSUE TITLE
Cannot find module '@openui5/themelib_sap_fiori_3/package.json

### ISSUE THREAD

**Issue by Subhani9090** [SAP/ui5-tooling#832]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to Reproduce the Issue

1. {...}
2. {...}
3. {...}

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`unknown`**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
{...}
```

**Comment by flovogt** [comment]
Hi @Subhani9090, thanks a lot for opening an issue here. Please provide further details about your scenario. Without we can not analyze your issue.
