### ISSUE TITLE
fiori deploy service parameter is missing

### ISSUE THREAD

**Issue by T1mey** [SAP/ui5-tooling#839]
Hello SAP,

we're missing a "--service" as a command line option for fiori deploy.

As the url parameter uses only the URL until the first / there is no option to use only command line parameters (--noConfig) with a different URL ending.

If we remove the --noConfig and add in the ui5-deploy.yaml a service the deployment is working as the system can be reached.

This does not behave in the right way. So in our opinion the param is missing.

**Comment by flovogt** [comment]
Hi and thanks for reaching out!

The custom task `deploy-to-abap` is part of the `@sap/ux-ui5-tooling` module which is not part of the UI5 Tooling project (our modules all start with @ui5/*). It is rather part of the SAP Fiori tools project, which is not open source as of today.

You can get in touch with the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

Or by asking your questions on the extension's page: https://marketplace.visualstudio.com/items?itemName=SAPSE.sap-ux-fiori-tools-extension-pack&ssr=false#qna

You can also find related documentation here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project. Also see https://github.com/SAP/ui5-tooling/issues/554#issuecomment-914472311, https://github.com/SAP/ui5-tooling/issues/532#issuecomment-874580387 and https://github.com/SAP/ui5-tooling/issues/418#issuecomment-669189877
