### ISSUE TITLE
When it will be official released? 

### ISSUE THREAD

**Issue by IlanaVek** [SAP/ui5-tooling#85]
## Expected Behavior
{...}

## Current Behavior
{...}

## Steps to reproduce the issue
1. {...}
2. {...}
3. {...}

## Context
- UI5 Module Version *(output of `ui5 --version` when using the CLI)*: `{...}`
- Node.js Version: `{...}`
- npm Version: `{...}`
- OS/Platform: {...}
- Browser *(if relevant)*: {...}
- Other information: {...}

## Affected components *(if known)*
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [ ] [ui5-server](https://github.com/SAP/ui5-server)
- [ ] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

## Log Output / Stack Trace
```
{...}
```

**Comment by RandomByte** [comment]
See https://github.com/SAP/ui5-tooling/issues/92
