### ISSUE TITLE
⚠️  Process Failed With Error  Error Message: The "path" argument must be of type string. Received undefined 

### ISSUE THREAD

**Issue by poonambatra07** [SAP/ui5-tooling#871]
Stack Trace: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined     at new NodeError (node:internal/errors:393:5)     at validateString (node:internal/validators:163:11)     at Object.resolve (node:path:1098:7)     at module.exports (/home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/ui5-middleware-cfdestination/lib/cfdestination.js:42:29)     at customMiddleware (file:///home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:313:53)     at async MiddlewareManager.addMiddleware (file:///home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:121:16)     at async MiddlewareManager.addCustomMiddleware (file:///home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:295:4)     at async MiddlewareManager.applyMiddleware (file:///home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/@ui5/cli/node_modules/@ui5/server/lib/middleware/MiddlewareManager.js:52:3)     at async serve (file:///home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/@ui5/cli/node_modules/@ui5/server/lib/server.js:178:2)     at async serve.handler (file:///home/poonam/AWA_NEW/awa-dom/workflow/ui/sandbox/node_modules/@ui5/cli/lib/cli/commands/serve.js:148:33)

**Comment by d3xter666** [comment]
Hi @poonambatra07 ,

Thank you for your ticket!

According to the stack trace, it seems more like an exception from the (ui5-middleware-cfdestination)[https://www.npmjs.com/package/ui5-middleware-cfdestination] package, then something from the UI5 Tooling.

Could you elaborate a bit more and provide a sample code/app where we could reproduce the issue?

Cheers

**Comment by poonambatra07** [comment]
Hi Yavor,

I'm getting following error on npm install

npm ERR! code ENOTFOUND
npm ERR! syscall getaddrinfo
npm ERR! errno ENOTFOUND
npm ERR! network request to
***@***.***/cli/-/cli-2.14.14.tgz
failed, reason: getaddrinfo ENOTFOUND
nginx-redirector.repo-cache.svc.cluster.local
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network
settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/poonam/.npm/_logs/2023-09-12T17_24_44_195Z-debug-0.log

**Comment by RandomByte** [comment]
> npm ERR! network This is a problem related to network connectivity.
> npm ERR! network In most cases you are behind a proxy or have bad network
settings.

I'm afraid this is an issue with your npm installation. We cannot help you here.
