### ISSUE TITLE
Inaccurate link in "Custom Bundling" section

### ISSUE THREAD

**Issue by dimovpetar** [SAP/ui5-tooling#879]
In this page https://sap.github.io/ui5-tooling/v3/pages/Configuration/#properties, there is a link to the API reference that should provide more information for the "embedding technologies". However, it leads to https://sap.github.io/ui5-tooling/v3/api/module-@ui5_builder_tasks_bundlers_generateBundle.html.
I believe it should lead to https://sap.github.io/ui5-tooling/v3/api/module-@ui5_builder_processors_bundlers_moduleBundler.html#~ModuleBundleDefinition

**Comment by d3xter666** [comment]
Thank you for catching this, @dimovpetar!
