### ISSUE TITLE
ui5 command error

### ISSUE THREAD

**Issue by vykuntoasis** [SAP/ui5-tooling#881]
Hi Team,

I am trying to use ui5 commands in Visual Studio code . 

My node js version is v18.15.0.

I installed using npm install -g @ui5/cli . But still am getting error that am unable to use ui5 commands

What else needs to be done or any thing need to be checked so that I can use ui5 commands

**Comment by d3xter666** [comment]
Hi @vykuntoasis ,

Can you elaborate a bit more?
Which is your operating system?
How do you install the CLI? 
Do you use `nvm` or some other tool like this?
What is the log from `npm install -g @ui5/cli`

It should be working normally after the install phase.

**Comment by vykuntoasis** [comment]
> Hi @vykuntoasis ,
> 
> Can you elaborate a bit more? Which is your operating system? How do you install the CLI? Do you use `nvm` or some other tool like this? What is the log from `npm install -g @ui5/cli`
> 
> It should be working normally after the install phase.

[](url)

**Comment by vykuntoasis** [comment]
hi @d3xter666 

please check the doc for full details

[error.docx](https://github.com/SAP/ui5-tooling/files/12914289/error.docx)

**Comment by vykuntoasis** [comment]
attached the doc for reference

**Comment by d3xter666** [comment]
Hi @vykuntoasis ,

It should be something with your environment, but not with `\@ui5\cli` itself. I have tested on Windows with PowerShell and CommandPrompt and in both cases it was working as expected.

I'd suggest several things to try out:

- Install another package with the global flag and try running.
- Check if your `PATH` env variable contains the `Roaming\npm` folder
- Run `npm list -g` to check whether `\@ui5/cli` has been installed on your system globally
- Install `\@ui5\cli` without the global flag and run it from within your app.

Cheers

**Comment by vykuntoasis** [comment]
I added environment variable Its working Thank you very much

Really struggled for so many days. I also tried environment path previously manually but I didn't put right ones

Thankyou
