### ISSUE TITLE
ui5.yaml version 1.114.8 of sapui5 fails during the build

### ISSUE THREAD

**Issue by robertiqkkk** [SAP/ui5-tooling#882]
Hello ui5-tooling team,

We are facing the error during the xmake build, after updating the ui5.yaml sapui5 version to `1.114.8`.
Please, check the logs in the below section, the root cause is marked with a sign '❌'.

<details>

<summary>Here is the log from the build:</summary>

### URL
*MB: Removed internal URL*

### Logs

13:56:57 INFO - info normalizer:translators:ui5Framework Using SAPUI5 version: `1.114.8`
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/distribution-metadata...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.suite.ui.generic.template...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.core...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ui.generic.app...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ushell...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.uxap...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/themelib_sap_belize...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/themelib_sap_fiori_3...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.rta...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.fe.placeholder...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.insights...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.f...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.m...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.fl...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.viz...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.suite.ui.microchart...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.layout...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ui.comp...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.table...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.fe.navigation...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.esh.search.ui...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.integration...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.collaboration...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ui.export...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.suite.ui.commons...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.dt...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.unified...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.chart...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.mdc...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ui.vbm...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ui.vk...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.commons...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @openui5/sap.ui.ux3...
13:56:57 INFO - info normalizer:ui5Framework:npm:Installer Installing missing package @sapui5/sap.ui.richtexteditor...
13:57:06 INFO - ..........
13:57:06 INFO - ⚠️ Process Failed With Error
13:57:06 INFO - 
13:57:06 INFO - Error Message:
13:57:06 INFO - Resolution of framework libraries failed with errors:
13:57:06 INFO - ❌Failed to resolve library sap.insights: Failed to extract package @sapui5/sap.insights@1.114.6: No matching version found for @sapui5/sap.insights@1.114.6.
13:57:06 INFO - ❌Failed to resolve library sap.suite.ui.commons: Failed to extract package @sapui5/sap.suite.ui.commons@1.114.6: No matching version found for @sapui5/sap.suite.ui.commons@1.114.6.
13:57:06 INFO - 
13:57:06 INFO - For details, execute the same command again with an additional '--verbose' parameter
13:57:06 INFO - [2023-10-16 10:57:06] ERROR could not build the "c4p-discipline-config-ui" module: could not execute the "npm run build" command: exit status 1
13:57:06 INFO - make: *** [Makefile_20231016105634.mta:37: c4p-discipline-config-ui] Error 1
13:57:06 ERROR - could not build the MTA project: could not execute the "make -f Makefile_20231016105634.mta p=CF mtar=c4p-discipline-config-ui.mtar strict=true mode= t=\"/xmake/j/prod-build10010/w/ght-copm/ght-copm-c4p-discipline-config-ui-SP-MS-linuxx86_64-linuxx86_64/gen/out\"" command: exit status 2
13:57:06 ERROR - JOB_FAILURE
13:57:06 xmake ERROR: mbt returned 1
13:57:06 ERROR - ====================================================================================================
13:57:06 ERROR - = workflow failed (-_-') =

</details>

## Expected Behavior
The build using `ui5 build` is not failing due to the ui5 tooling npm packages missing versions

## Current Behavior
Failure during the `ui5 build` with ui5.yaml sapui5 version having 1.114.8

## Steps to Reproduce the Issue

1. Set `1.114.8` version to the `ui5.yaml`
2. Run `ui5 build`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`1.114.8`**
 * Node.js Version: **`18.13.0`**
 * npm Version: `unknown`
 * OS/Platform: `unknown`
 * Browser *(if relevant)*: `unknown`
 * Other information regarding your environment *(optional)*: `nothing`

**Comment by codeworrior** [comment]
According to https://ui5.sap.com/1.114.8/patchinfo.html, it's correct that [@sapui5/sap.insight@1.114.6](https://www.npmjs.com/package/@sapui5/sap.insights/v/1.114.6) and [@sapui5/sap.suite.ui.commons@1.114.6](https://www.npmjs.com/package/@sapui5/sap.suite.ui.commons/v/1.114.6) should be requested, but obviously their publishing failed :-(

The same errors should occur for SAPUI5 1.114.7, it references the same patch levels of those libs.

**Comment by RandomByte** [comment]
Apologies for the inconvenience. Sadly the release process of the npm packages for SAPUI5 1.114.7 failed at first and it was missed to trigger it again.

I triggered another published earlier and the missing versions are now available.
