### ISSUE TITLE
Illustrated Message: ResourceBundle: value for parameter 'aArgs' is not of type array

### ISSUE THREAD

**Issue by whydrae** [SAP/ui5-tooling#895]
## Expected Behavior
No errors in the console.

## Current Behavior
When using `sap.m.sample.IllustratedMessage`, I see a lot of errors in the console: `sap/base/i18n/ResourceBundle: value for parameter 'aArgs' is not of type array`.

## Steps to Reproduce the Issue

1. Open any Illustrated Message sample, for example: https://ui5.sap.com/#/entity/sap.m.IllustratedMessage/sample/sap.m.sample.IllustratedMessageEVR
2. Open console and find the errors

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): since **`1.119.0`**
 * OS/Platform: `Mac Os`
 * Browser *(if relevant)*: `Edge`

**Comment by whydrae** [comment]
False repo, sorry.

**Comment by RandomByte** [comment]
Thanks for letting us know. No problem. I will delete the issue momentarily.
