### ISSUE TITLE
Git hub deployment of subfolders and its contents

### ISSUE THREAD

**Issue by vykuntoasis** [SAP/ui5-tooling#912]
Hi Team,

Am facing issue while moving content from subfolder.

[Githuberror.pdf](https://github.com/SAP/ui5-tooling/files/13710407/Githuberror.pdf)

**Comment by RandomByte** [comment]
I'm sorry but this does not seem related to this project at all. I would recommend reaching out to [GitHub Support](https://support.github.com/) instead.
