### ISSUE TITLE
Hot-reload not working for start-local

### ISSUE THREAD

**Issue by RuckertSolutions** [SAP/ui5-tooling#922]
Hi,

when starting a brand new project (`npm run start-local`), hot reloading does not work for local development, but it does for `npm run start`.

## Expected Behavior
A change in a controller or view file should trigger hot reload like the `npm run start` script does.

## Current Behavior
A change in a controller or view file does not trigger hot-reload, even though `fiori-tools-appreload` is in the customMiddleware of the `ui5-local.yaml`.

## Steps to Reproduce the Issue

1. Open App generator.
2. Choose Basic Template.
3. No DataSource.
4. Advanced options: Eslint, Code assist libs and Typescript YES.
5. Run `npm start-local` and make a change to a file, it will not reload automatically.

## Context
 * UI5 Module Version: @ui5/cli": "^3.0.0
 * Node.js Version: 18.15.0 LTS
 * npm Version: 9.5.0
 * OS/Platform: Windows 11
 * Browser *(if relevant)*: Edge
 * Other information regarding your environment *(optional)*: `Nothing`

**Comment by d3xter666** [comment]
Hi @RuckertSolutions,

The UI5 Tooling does not provide hot reload out of the box. Maybe, it's an UI5 Tooling middleware or it's some setup that provides this on its own.
Unfortunately, we are not able to support and can provide only guesses without the content of the package.json file.
And still, I believe, it's rather a setup thing, than something in the UI5 Tooling itself.

Cheers
