### ISSUE TITLE
unable to use ui5/cli 3.* version

### ISSUE THREAD

**Issue by rabi84** [SAP/ui5-tooling#934]
Hi Team,

I am trying to migrate ui5/cli from 2.* version to 3.* version in UI repo, which contains one lib which also uses ui5/cli. Now I am getting the below error, I tried my best to fix but no clue yet, could you please help me on this.

**verb graph:Module Could not find any build manifest in module ui-root
verb graph:Module Could not find a configuration file for module ui-root**

⚠️  Process Failed With Error

Error Message:
Failed to create a UI5 project from module ui-root at /Users/YYY/ui. Make sure the path is correct and a project configuration is present or supplied.

Stack Trace:
Error: Failed to create a UI5 project from module ui-root at /Users/YYY/ui. Make sure the path is correct and a project configuration is present or supplied.
    at projectGraphBuilder (file:///Users/YYY/ui/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/projectGraphBuilder.js:120:9)
    at async graphFromPackageDependencies (file:///Users/YYY/ui/node_modules/@ui5/cli/node_modules/@ui5/project/lib/graph/graph.js:73:23)
    at async Object.handleBuild [as handler] (file:///Users/YYY/ui/node_modules/@ui5/cli/lib/cli/commands/build.js:165:11)

**Comment by flovogt** [comment]
Hi @rabi84,
thanks a lot for opening this issue. Could you share your project with us (github repo or zipped project)? In case your project is related to an SAP customer, feel free to open a customer case on https://support.sap.com/ and share the project there.

**Comment by flovogt** [comment]
Its important to execute the `ui5 build` or `ui5 serve` command in the project root directory, where the `ui5.yaml` and `package.json` have to be located

**Comment by rabi84** [comment]
I am executing commands in root dirtectory only.
let me check with team if I can share the project repo here.
Thanks
