### ISSUE TITLE
In Build process of sapui5 application, facing some issues. 

### ISSUE THREAD

**Issue by SatishNaani** [SAP/ui5-tooling#951]
## Expected Behavior
We have a UI5 project and we followed a standard approach to build the application. We are facing some issue while building it.

## Current Behavior
Used third party NPM resources xml-js , getting below error.

[package.json](https://github.com/SAP/ui5-tooling/files/15188525/package.json)
[ui5.txt](https://github.com/SAP/ui5-tooling/files/15188530/ui5.txt)
**Error:**
"builder:custom-task:ui5-tooling-modules-task Failed to rewrite "xml-js/tsMode"! Ignoring resource... (maybe an ES module you included as asset by mistake?)"

## Steps to Reproduce the Issue

I uploaded the **package.json** and **ui5.yaml** we used in our project, while building this we are facing the error.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **`3.9.0`**
 * Node.js Version: 18.18.2
 * npm Version: 9.8.1
 * OS/Platform: Windows 10 in webstorm
 * Browser *(if relevant)*: `chrome`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

```
[{...}](builder:custom-task:ui5-tooling-modules-task Failed to rewrite "xml-js/tsMode"! Ignoring resource... (maybe an ES module you included as asset by mistake?))
```

**Comment by matz3** [comment]
The [ui5-tooling-modules extension](https://github.com/ui5-community/ui5-ecosystem-showcase/tree/main/packages/ui5-tooling-modules) is part of the [ui5-community/ui5-ecosystem-showcase](https://github.com/ui5-community/ui5-ecosystem-showcase) project.
As this is most likely related to the extension, not UI5 Tooling itself, please first create an issue there: https://github.com/ui5-community/ui5-ecosystem-showcase/issues/new/choose
