### ISSUE TITLE
An unexpected error occurred, Could not find any project root. Parameter 'sapuxRequired' was true.

### ISSUE THREAD

**Issue by ManirajanV** [SAP/ui5-tooling#953]
## Expected Behavior
Should be able to visualize the Annotation file and modify it.

## Current Behavior
Throwing error "An unexpected error occurred, Could not find any project root. Parameter 'sapuxRequired' was true." 
**I could not find any setting / document releted to this.**

## Steps to Reproduce the Issue
1. Open **Annotation Modeler** from Extension "**SAP Fiori Tools - Service Modeler**" to visualize the annotaiton file locally created.

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **` 3.10.0`**
 * Node.js Version: **`v20.12.0`**
 * npm Version: `10.5.0`
 * OS/Platform: `BAS tool (Free Version)`
 * Browser *(if relevant)*: `Not Relevant`
 * Other information regarding your environment *(optional)*: `nothing`

## Log Output / Stack Trace

Throwing error "**An unexpected error occurred, Could not find any project root. Parameter 'sapuxRequired' was true.**" 
<img width="658" alt="BAS Error" src="https://github.com/SAP/ui5-tooling/assets/66389855/6a8bf2a3-6a1a-4079-992b-2c185d31a752">

**Comment by d3xter666** [comment]
Hi and thanks for reaching out.

Unfortunatelly, this issue does not seem to be related to the UI5 Tooling, but to Fiori Tools. Please refer to the SAP Fiori tools team via the SAP Community Website: https://community.sap.com/topics/fiori-tools

You can also find related documentation and support channels for Fiori tools here: https://help.sap.com/viewer/product/SAP_FIORI_tools/Latest/en-US

I'll close this issue as it is not related to this project.
