### ISSUE TITLE
ui5 serve --open can not resolve relative path with single quote 'xxxxxx'

### ISSUE THREAD

**Issue by geng19** [SAP/ui5-tooling#971]
ui5 serve --open will open web server root directory in default browser. Optionally, supplied relative path will be appended to the root URL. But when i use it in my case, the relative path was with '' and it had the error ''failed to load resource: the server responded with a status of 404 (not found)''

code with error :
"scripts": {
    "start": "ui5 serve --open 'index.html'"
  },
but it worked with        \"index.html\"     or  just index.html without prefix and suffix

**Comment by flovogt** [comment]
Hi @geng19,
thanks for sharing this finding. I tested it on my machine (macos v14.5, node v20.13.1, ui5/cli v3.11.0). With following 3 options the index.html opens as desired in my default browser.
1. `ui5 serve --open index.html`
2. `ui5 serve --open "index.html"`
3. `ui5 serve --open 'index.html'`
So, I guess your machine/os differs from my one. Could you please share your operating system, installed node version and @ui5/cli version?

**Comment by geng19** [comment]
Node.js v20.12.0
[image: image.png]

Florian Vogt ***@***.***> 于2024年6月27日周四 07:50写道：

**Comment by RandomByte** [comment]
> Node.js v20.12.0 [image: image.png]

Sadly that image didn't go through. Could you please try uploading it via a new comment in the browser?

**Comment by RandomByte** [comment]
Also, please share your npm version as well as your operating system with us. Thanks!
