### ISSUE TITLE
Live reload

### ISSUE THREAD

**Issue by alexanderchan** [SAP/ui5-tooling#99]
## Expected Behavior
Server is a live reload and bonus points for supporting hot module replacement.  Perhaps I missed it.

## Current Behavior
Server is static 

## Steps to reproduce the issue
1. ui5 serve
2. change a file (html, js, xml etc)
3. wait
4. nothing happens
5. refresh your browser yourself like it's 2013 :laughing: 

- sorry I'm so lazy but the movement to developer experience has spoiled me.  browsersync had this back in the day and every modern cli tool does it out of the box (create-react-app, vue cli, angular probably) as well as (or because of) the usual build systems (see webpack, parcel)

## Context
- ui5 serve

## Affected components *(if known)*
- [ ] [ui5-builder](https://github.com/SAP/ui5-builder)
- [x] [ui5-server](https://github.com/SAP/ui5-server)
- [x] [ui5-cli](https://github.com/SAP/ui5-cli)
- [ ] [ui5-fs](https://github.com/SAP/ui5-fs)
- [ ] [ui5-project](https://github.com/SAP/ui5-project)
- [ ] [ui5-logger](https://github.com/SAP/ui5-logger)

I know it's not as easy to make the cli like create-react-app or vue but they're really the gold standard and we should strive for that

**Comment by mahendra3006** [comment]
When can we expect this functionality.We badly need this,as we need to login into our app again after each refresh.

**Comment by matz3** [comment]
Regarding live reload, you might have a look into our BrowserSync example, to see how you can use it with our tooling already:
https://github.com/SAP/ui5-tooling/tree/master/examples/browsersync

**Comment by mahendra3006** [comment]
Thank you for the quick response.It reloads the change when there is an update,but I was looking for hot module replacement so that I do not need to reload the page after each change in UI.
In my project login takes about 2 minutes and then to navigate to the screen also takes good amount of time.

**Comment by matz3** [comment]
Unfortunately, I did not have a deeper look into how hot module replacement is done in frameworks like react or vue.
But I would expect that this can not be easily integrated into UI5, as the framework hasn't been designed for it.
This needs to be investigated to see whether it would be possible at all.
So some input on this would be much appreciated 👍

**Comment by matz3** [comment]
> In my project login takes about 2 minutes and then to navigate to the screen also takes good amount of time

Isn't that something that could be addressed on your side?
The session should not be invalidated, just by refreshing the page. And when using a router with hash based URL navigation, the refresh should bring you to the same page as before the refresh.

**Comment by mahendra3006** [comment]
We have a custom router without hash routing.
Also, we have multiple apps inside a main app which has the login functionality.
Running any one app in isolation is also not possible.

**Comment by fatschi** [comment]
https://github.com/petermuessig/ui5-ecosystem-showcase/tree/master/packages/ui5-middleware-livereload might be helpful!?

**Comment by alexanderchan** [comment]
Don’t need this anymore as am not using ui5
