### ISSUE TITLE
 Button: Type="Ghost" (Secondary) has a Different Visual Design in Headers

### ISSUE THREAD

**Issue by eric-hoffmann-sap** [SAP/ui5-tooling#993]
## Expected Behavior
The visual design of buttons using type=“Ghost” is a) consistent and independent of the parent container, and b) according to the [visual design specification](https://wiki.one.int.sap/wiki/pages/viewpage.action?pageId=2698912599).

## Current Behavior
The visual design of buttons using type=“Ghost” is different depending on the parent container, for example, when placed in a header compared to the content. [Open Screen Recording](https://sap-my.sharepoint.com/personal/eric_hoffmann_sap_com/_layouts/15/stream.aspx?id=%2Fpersonal%2Feric%5Fhoffmann%5Fsap%5Fcom%2FDocuments%2FPublic%2FScreen%20Recording%202024%2D07%2D25%20at%2016%2E43%2E19%2Emov&ga=1&referrer=StreamWebApp%2EWeb&referrerScenario=AddressBarCopied%2Eview%2E7af15166%2D5ab6%2D4782%2Db727%2D7b60e89b5fdf). Bug according to the SAP Fiori for Web team. [Open Email](https://sap-my.sharepoint.com/:u:/p/eric_hoffmann/EcQeoxfb5YdOtxGmuRBpJkUBnAzwenLQ8gwWcBqJwbntQQ?e=eZwgDd).

## Steps to Reproduce the Issue
1. Open a [UI5 Sampel](https://sapui5nightly.int.sap.eu2.hana.ondemand.com/#/entity/sap.m.Button/sample/sap.m.sample.Button/code)
2. Enter the following code: 
`<mvc:View
	xmlns="sap.m"
	xmlns:mvc="sap.ui.core.mvc"
	xmlns:core="sap.ui.core"
	height="100%"
	controllerName="sap.m.sample.Button.Page">
	<Page
		title="Page"
		class="sapUiContentPadding" >
		<customHeader>
			<Toolbar>
				<Button text="Default / Ghost"
						press="Ghost">
				</Button>
				<Button text="Transparent"
						type="Transparent">
				</Button>
			</Toolbar>
		</customHeader>
		<content>
			<HBox>
				<Button text="Default / Ghost"
						press="Ghost">
				</Button>
				<Button text="Transparent"
						type="Transparent">
				</Button>
			</HBox>
		</content>
	</Page>
</mvc:View>`

## Context
 * UI5 Module Version (output of `ui5 --version` when using the CLI): **1.128**
 * Node.js Version: **`unknown`**
 * npm Version: `unknown`
 * OS/Platform: `macOS`
 * Browser *(if relevant)*: `Microsoft Edge 127.0.2651.74`
 * Other information regarding your environment *(optional)*: `nothing`

**Comment by d3xter666** [comment]
Hi @eric-hoffmann-sap ,

Thank you for your feedback!
Unfortunately, this repo is meant for ui5-tooling issues only. Please raise your concerns into the respective repository: https://github.com/SAP/openui5

Please, also bare in mind not to expose any sap internal information. Instead you can use the internal channels for that!

Cheers
