### ISSUE TITLE
Broken link in "UI5 Project # library" documentation

### ISSUE THREAD

**Issue by Thodd** [SAP/ui5-tooling#994]
## Expected Behavior

The link to the`controllibraries.md` documentation in OpenUI5 should be accessible from this page:
https://sap.github.io/ui5-tooling/v4/pages/Project/#library

## Current Behavior

The link to the`controllibraries.md` documentation points to the `main` branch instead of the `master` branch:

https://github.com/SAP/openui5/blob/main/docs/controllibraries.md

vs.

https://github.com/SAP/openui5/blob/master/docs/controllibraries.md

## Context
 * Link is correct in [V2](https://sap.github.io/ui5-tooling/v2/pages/Builder/#library), broken since [V3](https://sap.github.io/ui5-tooling/v3/pages/Project/#library)

**Comment by flovogt** [comment]
Thanks @Thodd, I will take care.
